<div class="modal fade" id="editNewEvent" aria-hidden="true" aria-labelledby="editNewEvent"
  role="dialog" tabindex="-1" data-show="false">
  <div class="modal-dialog modal-simple modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="modal-title"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body body-event">
        <div class="col-12">
          <div class="example-wrap mt-50px">
            <div class="example-loading vertical-align text-center pt-100">
              <div class="loader vertical-align-middle loader-tadpole"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>