<div class="modal fade" id="editNewEvent" aria-hidden="true" aria-labelledby="editNewEvent"
  role="dialog" tabindex="-1" data-show="false">
  <div class="modal-dialog modal-simple modal-lg">
    <div class="modal-content" style="height:100%;">
      <div class="modal-header">
        <h4 class="modal-title" id="modal-title"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <h4 class="text-uppercase text-center col-12"><i class="icon wb-check-circle" aria-hidden="true"></i>Your Disponibility</h4>
          <div class="btn-group btn-group-justified mt-20 mb-40">
            <div class="btn-group" role="group">
              <a id="event-url-ok" href="#" class="btn btn-present">
                <i class="icon wb-check-circle" aria-hidden="true"></i>
                <br>
                <span class="text-uppercase">In</span>
              </a>
            </div>

            <div class="btn-group" role="group">
              <a id="event-url-no" href="#" class="btn btn-absent">
                <i class="icon wb-minus-circle" aria-hidden="true"></i>
                <br>
                <span class="text-uppercase">Out</span>
              </a>
            </div>

            <div class="btn-group mt-40" role="group">
              <a id="event-url-incertain" href="#" class="btn btn-uncertain">
                <i class="icon wb-help-circle" aria-hidden="true"></i>
                <br>
                <span class="text-uppercase">Uncertain</span>
              </a>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <h4 class="text-uppercase" id="modal-title"></h4>
              <div class="card card-inverse overlay">
                <img class="card-img overlay-figure" src="/img/email-header.jpeg" alt="...">
                <div class="card-img-overlay overlay-background text-center vertical-align">
                  <div class="vertical-align-middle">
                    <div class="card-text card-divider">
                      <span id="modal-date"></span>
                    </div>
                    <h3 class="card-title mb-10" id="modal-place"></h3>
                    <p><span class="card-title mb-10"><span id="modal-address"></span>, <span id="modal-zipcode"></span> <span id="modal-city"></span></span></p>
                    <div class="btn-group btn-group-justified mt-20 mb-40">
                      <div class="btn-group" role="group">
                        <a href="#" class="btn btn-outline btn-default" id="event-place-url" target="_blank">
                          <i class="icon wb-map" aria-hidden="true"></i>
                          <br>
                          <span class="text-uppercase">go to map</span>
                        </a>
                      </div>

                      <div class="btn-group" role="group">
                        <a href="#" class="btn btn-outline btn-info event-url">
                          <i class="icon wb-eye" aria-hidden="true"></i>
                          <br>
                          <span class="text-uppercase">See details</span>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <div class="example-wrap mt-20 mb-0">
                <div class="nav-tabs-horizontal" data-plugin="tabs">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item" role="presentation">
                      <a class="nav-link active show" data-toggle="tab" href="#exampleTabsIconOne" aria-controls="exampleTabsIconOne" role="tab" aria-selected="true">
                        <span>
                          <i class="icon wb-check-circle text-present" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info" id="event-count-ok"></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconTwo" aria-controls="exampleTabsIconTwo" role="tab" aria-selected="false">
                        <span>
                          <i class="icon wb-minus-circle text-absent" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info" id="event-count-no"></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconThree" aria-controls="exampleTabsIconThree" role="tab" aria-selected="false">
                        <span>
                          <i class="icon wb-help-circle text-uncertain" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info" id="event-count-uncertain"></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconFour" aria-controls="exampleTabsIconFour" role="tab">
                        <span>
                          <i class="icon wb-alert-circle text-no-answer" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info" id="event-count-no-answer"></span>
                        </span>
                      </a>
                    </li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active show" id="exampleTabsIconOne" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-ok">
                            <td class="text-center">NO USER</td>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconTwo" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-no">
                            <td class="text-center">NO USER</td>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconThree" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-uncertain">
                            <td class="text-center">NO USER</td>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconFour" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-no-answer">
                            <td class="text-center">NO USER</td>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>