<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
      data-toggle="menubar">
      <span class="sr-only">Toggle navigation</span>
      <span class="hamburger-bar"></span>
    </button>
    <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
      data-toggle="collapse">
      <i class="icon wb-more-horizontal" aria-hidden="true"></i>
    </button>
    <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
      <img class="navbar-brand-logo" src="/assets/images/logo.png" title="Volley-ball.eu">
      <span class="navbar-brand-text hidden-xs-down"> Volley-ball.eu</span>
    </div>
    <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search"
      data-toggle="collapse">
      <span class="sr-only">Toggle Search</span>
      <i class="icon wb-search" aria-hidden="true"></i>
    </button>
  </div>

  <div class="navbar-container container-fluid">
    <!-- Navbar Collapse -->
    <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
      <!-- Navbar Toolbar -->
      <ul class="nav navbar-toolbar">
        <li class="nav-item hidden-float" id="toggleMenubar">
          <a class="nav-link" data-toggle="menubar" href="#" role="button">
            <i class="icon hamburger hamburger-arrow-left">
              <span class="sr-only">Toggle menubar</span>
              <span class="hamburger-bar"></span>
            </i>
          </a>
        </li>
        <li class="nav-item hidden-sm-down" id="toggleFullscreen">
          <a class="nav-link icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
            <span class="sr-only">Toggle fullscreen</span>
          </a>
        </li>
       <!--  <li class="nav-item hidden-float">
          <a class="nav-link icon wb-search" data-toggle="collapse" href="#" data-target="#site-navbar-search"
            role="button">
            <span class="sr-only">Toggle Search</span>
          </a>
        </li> -->
      </ul>
      <!-- End Navbar Toolbar -->

      <!-- Navbar Toolbar Right -->
      <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" data-animation="scale-up"
            aria-expanded="false" role="button">
            <span class="flag-icon flag-icon-gb"></span>
          </a>
          <div class="dropdown-menu" role="menu">
            <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
              <span class="flag-icon flag-icon-gb"></span> English</a>
<!--             <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
              <span class="flag-icon flag-icon-fr"></span> French
            </a> -->
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"
            data-animation="scale-up" role="button">
            <span class="avatar">
              <img src="<?= (isset($user)) ? $user->getAvatarPath() : '/img/avatars/default-avatar.png';?>">
            </span>
          </a>
          <div class="dropdown-menu" role="menu">
            <a class="dropdown-item" href="/user/profile" role="menuitem"><i class="icon wb-user" aria-hidden="true"></i> Profile</a>
            <div class="dropdown-divider" role="presentation"></div>
            <a class="dropdown-item" href="/auth/signout" role="menuitem"><i class="icon wb-power" aria-hidden="true"></i> Logout</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)"
            aria-expanded="false" data-animation="scale-up" role="button">
            <i class="icon wb-bell" aria-hidden="true"></i>
            <span class="badge badge-pill badge-danger up"><?= count($notifications) ?></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
            <div class="dropdown-menu-header">
              <h5>NOTIFICATIONS</h5>
              <span class="badge badge-round badge-danger">New <?= count($notifications) ?></span>
            </div>

            <div class="list-group">
              <div data-role="container">
                <div data-role="content">
                  <?php foreach ($notifications as $notification): ?>
                    <div class="list-group-item dropdown-item" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <span class="avatar img-bordered avatar-30" href="javascript:void(0)">
                            <img src="<?= $notification['group']->getAvatarPath() ?>">
                          </span>
                        </div>
                        <div class="media-body">
                          <div class="row">
                            <div class="col-7">
                              <h6 class="media-heading"><?= $notification['event']->name ?></h6>
                              <time class="media-meta">In <?= \Application\Service\Date::getInterval(\DateTime::createFromFormat('Y-m-d H:i:s', $notification['event']->date), new \DateTime()) ?></time>
                            </div>
                            <div class="col-5 text-right">
                              <button type="button" class="btn btn-icon btn-success btn-outline btn-round"><i class="icon wb-check m-0" aria-hidden="true"></i></button>
                              <button type="button" class="btn btn-icon btn-danger btn-outline btn-round"><i class="icon wb-close m-0" aria-hidden="true"></i></button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <?php endforeach ?>
                </div>
              </div>
            </div>
        </li>
      </ul>
      <!-- End Navbar Toolbar Right -->
    </div>
    <!-- End Navbar Collapse -->

    <!-- Site Navbar Seach -->
    <div class="collapse navbar-search-overlap" id="site-navbar-search">
      <form role="search">
        <div class="form-group">
          <div class="input-search">
            <i class="input-search-icon wb-search" aria-hidden="true"></i>
            <input type="text" class="form-control" name="site-search" placeholder="Search...">
            <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
              data-toggle="collapse" aria-label="Close"></button>
          </div>
        </div>
      </form>
    </div>
    <!-- End Site Navbar Seach -->
  </div>
</nav>