<div class="page-aside">
  <div class="page-aside-switch">
    <i class="icon wb-chevron-left" aria-hidden="true"></i>
    <i class="icon wb-chevron-right" aria-hidden="true"></i>
  </div>
  <div class="page-aside-inner page-aside-scroll">
    <div data-role="container">
      <div data-role="content">
        <section class="page-aside-section">
          <h5 class="page-aside-title">GROUP LIST</h5>
          <div class="list-group has-actions">
            <?php if ($this->groups): ?>
              <?php foreach ($this->groups as $group): ?>
                  <div class="list-group-item" data-plugin="editlist">
                    <div class="list-content">
                      <span class="item-right">10</span>
                      <span class="list-text"><?= $group->name ?></span>
                      <div class="item-actions">
                        <span class="btn btn-pure btn-icon" data-toggle="list-visible"><i class="icon wb-eye" aria-hidden="true"></i></span>
                      </div>
                    </div>
                  </div>
              <?php endforeach ?>
            <?php endif ?>
          </div>
        </section>
        <section class="page-aside-section">
          <div class="list-group calendar-list">
            <a id="addNewEventBtn" class="list-group-item" href="javascript:void(0)"> <i class="icon wb-plus" aria-hidden="true"></i> Add New Event </a>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>