    <div class="site-menubar">
      <div class="site-menubar-body">
        <ul class="site-menu" data-plugin="menu">
          <li class="site-menu-category">Menu</li>
          <li class="site-menu-item">
            <a href="javascript:void(0)">
              <i class="site-menu-icon wb-calendar" aria-hidden="true"></i>
              <span class="site-menu-title">Calendar</span>
            </a>
          </li>
          <li class="site-menu-item">
            <a href="javascript:void(0)">
              <i class="site-menu-icon wb-user-circle" aria-hidden="true"></i>
              <span class="site-menu-title">Profile</span>
            </a>
          </li>
          <li class="site-menu-item">
            <a href="javascript:void(0)">
              <i class="site-menu-icon wb-heart-outline" aria-hidden="true"></i>
              <span class="site-menu-title">Holidays</span>
            </a>
          </li>
          <li class="site-menu-item">
            <a href="javascript:void(0)">
              <i class="site-menu-icon wb-plus" aria-hidden="true"></i>
              <span class="site-menu-title">New Group</span>
            </a>
          </li>
          <li class="divider"></li>
          <li class="site-menu-item">
            <a href="javascript:void(0)">
              <i class="site-menu-icon wb-power" aria-hidden="true"></i>
              <span class="site-menu-title">logout</span>
            </a>
          </li>
        </ul>
      </div>
        <div class="site-menubar-footer">
          <a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
            <span class="icon wb-power" aria-hidden="true"></span>
          </a>
        </div>
      </div>
      <div class="site-gridmenu">
        <ul>
          <li>
            <a href="../../apps/mailbox/mailbox.html">
              <i class="icon wb-envelope"></i>
              <span>Mailbox</span>
            </a>
          </li>
          <li>
            <a href="../../apps/calendar/calendar.html">
              <i class="icon wb-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="../../apps/contacts/contacts.html">
              <i class="icon wb-user"></i>
              <span>Contacts</span>
            </a>
          </li>
          <li>
            <a href="../../apps/media/overview.html">
              <i class="icon wb-camera"></i>
              <span>Media</span>
            </a>
          </li>
          <li>
            <a href="../../apps/documents/categories.html">
              <i class="icon wb-order"></i>
              <span>Documents</span>
            </a>
          </li>
          <li>
            <a href="../../apps/projects/projects.html">
              <i class="icon wb-image"></i>
              <span>Project</span>
            </a>
          </li>
          <li>
            <a href="../../apps/forum/forum.html">
              <i class="icon wb-chat-group"></i>
              <span>Forum</span>
            </a>
          </li>
          <li>
            <a href="../../index.html">
              <i class="icon wb-dashboard"></i>
              <span>Dashboard</span>
            </a>
          </li>
        </ul>
    </div>