    <div class="site-menubar">
      <div class="site-menubar-body">
        <ul class="site-menu" data-plugin="menu">
          <li class="site-menu-category">Menu</li>
          <li class="site-menu-item">
            <a href="/">
              <i class="site-menu-icon wb-calendar" aria-hidden="true"></i>
              <span class="site-menu-title">Calendar</span>
            </a>
          </li>
          <li class="site-menu-item">
            <a href="/user/profile" class="pl-20">
              <!-- <i class="site-menu-icon wb-user-circle" aria-hidden="true"></i> -->
              <i class="avatar avatar-md"><img src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-group-avatar.png') this.src = '/img/default-group-avatar.png';"></i>
              <span class="site-menu-title">Profile</span>
            </a>
          </li>
          <li class="site-menu-item">
            <a href="/group/create">
              <i class="site-menu-icon wb-plus" aria-hidden="true"></i>
              <span class="site-menu-title">New Group</span>
            </a>
          </li>
          <?php foreach ($groups as $group): ?>
            <li class="site-menu-item">
              <a href="/welcome-to/<?= $group->brand ?>" class="pl-20">
                <!-- <i class="site-menu-icon wb-user-circle" aria-hidden="true"></i> -->
                <i class="avatar avatar-md"><img src="<?= $group->getAvatarPath() ?>" onerror="if (this.src != '/img/default-group-avatar.png') this.src = '/img/default-group-avatar.png';"></i>
                <span class="site-menu-title"><?= $group->name ?></span>
              </a>
            </li>
          <?php endforeach ?>
          <li class="divider"></li>
          <li class="site-menu-item">
            <a href="/auth/signout">
              <i class="site-menu-icon wb-power" aria-hidden="true"></i>
              <span class="site-menu-title">logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
      <!-- <div class="site-gridmenu">
        <ul>
          <li>
            <a href="../../apps/mailbox/mailbox.html">
              <i class="icon wb-envelope"></i>
              <span>Mailbox</span>
            </a>
          </li>
          <li>
            <a href="../../apps/calendar/calendar.html">
              <i class="icon wb-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="../../apps/contacts/contacts.html">
              <i class="icon wb-user"></i>
              <span>Contacts</span>
            </a>
          </li>
          <li>
            <a href="../../apps/media/overview.html">
              <i class="icon wb-camera"></i>
              <span>Media</span>
            </a>
          </li>
          <li>
            <a href="../../apps/documents/categories.html">
              <i class="icon wb-order"></i>
              <span>Documents</span>
            </a>
          </li>
          <li>
            <a href="../../apps/projects/projects.html">
              <i class="icon wb-image"></i>
              <span>Project</span>
            </a>
          </li>
          <li>
            <a href="../../apps/forum/forum.html">
              <i class="icon wb-chat-group"></i>
              <span>Forum</span>
            </a>
          </li>
          <li>
            <a href="../../index.html">
              <i class="icon wb-dashboard"></i>
              <span>Dashboard</span>
            </a>
          </li>
        </ul>
    </div> -->