<?php $eventDate   = \DateTime::createFromFormat('Y-m-d H:i:s', $event->date); ?>
<div class="row">

    <!-- Left Side -->
    <div class="col-sm-4">
        <div class="card card-inverse overlay mb-20">
          <img class="card-img overlay-figure h-only-xs-250 h-only-sm-250" src="/img/email-header.jpeg" alt="...">
          <div class="card-img-overlay overlay-background text-center vertical-align">
            <div class="vertical-align-middle">
              <div class="card-text card-divider">
                <span>July 28, 2017 <br> 20:00</span>
              </div>
              <h3 class="card-title mb-20"><?= $event->name ?></h3>
              <p><span class="card-title mb-10"><?= $event->address ?>, <?= $event->zipCode ?> <?= $event->city ?></span></p>
              <div class="btn-group btn-group-justified mt-20 mb-20">
                <div class="btn-group" role="group">
                  <a id="event-url-ok" href="#" class="btn btn-outline btn-inverse">
                    <i class="icon wb-camera" aria-hidden="true"></i>
                    <br>
                    <span class="text-uppercase">Live Score</span>
                  </a>
                </div>
                <div class="btn-group" role="group">
                  <a id="event-url-no" href="#" class="btn btn-outline btn-primary">
                    <i class="icon wb-stats-bars" aria-hidden="true"></i>
                    <br>
                    <span class="text-uppercase">See Stats</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="col-sm-4">
      <div class="card card-shadow">
        <div class="btn-group btn-group-justified mt-0 mb-0">
          <div class="btn-group" role="group">
            <a href="/disponibility/response/<?= $event->id ?>/<?= Application\Model\Disponibility::RESP_OK ?>" class="btn btn-present">
              <i class="icon wb-check-circle" aria-hidden="true"></i>
              <br>
              <span class="text-uppercase">In</span>
            </a>
          </div>
          <div class="btn-group" role="group">
            <a href="/disponibility/response/<?= $event->id ?>/<?= Application\Model\Disponibility::RESP_NO ?>" class="btn btn-absent">
              <i class="icon wb-minus-circle" aria-hidden="true"></i>
              <br>
              <span class="text-uppercase">Out</span>
            </a>
          </div>
          <div class="btn-group mt-40" role="group">
            <a href="/disponibility/response/<?= $event->id ?>/<?= Application\Model\Disponibility::RESP_UNCERTAIN ?>" class="btn btn-uncertain">
              <i class="icon wb-help-circle" aria-hidden="true"></i>
              <br>
              <span class="text-uppercase">Uncertain</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Disponibility card -->
      <div class="card card-shadow">
          <div class="card-block">
              <div class="example-wrap mt-20 mb-0">
                <div class="nav-tabs-horizontal" data-plugin="tabs">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item" role="presentation">
                      <a class="nav-link active show" data-toggle="tab" href="#exampleTabsIconOne" aria-controls="exampleTabsIconOne" role="tab" aria-selected="true">
                        <span>
                          <i class="icon wb-check-circle text-present" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info float-right"><?= $counters[Application\Model\Disponibility::RESP_OK] ?></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconTwo" aria-controls="exampleTabsIconTwo" role="tab" aria-selected="false">
                        <span>
                          <i class="icon wb-minus-circle text-absent" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info float-right"><?= $counters[Application\Model\Disponibility::RESP_NO] ?></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconThree" aria-controls="exampleTabsIconThree" role="tab" aria-selected="false">
                        <span>
                          <i class="icon wb-help-circle text-uncertain" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info float-right"><?= $counters[Application\Model\Disponibility::RESP_UNCERTAIN] ?></span>
                        </span>
                      </a>
                    </li>
                    <li class="nav-item" role="presentation">
                      <a class="nav-link" data-toggle="tab" href="#exampleTabsIconFour" aria-controls="exampleTabsIconFour" role="tab">
                        <span>
                          <i class="icon wb-alert-circle text-no-answer" style="font-size:24px;" aria-hidden="true"></i>
                          <span class="badge badge-pill up badge-info float-right"><?= $counters[Application\Model\Disponibility::RESP_NO_ANSWER] ?></span>
                        </span>
                      </a>
                    </li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active show" id="exampleTabsIconOne" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-ok">
                            <?php if (!$users[Application\Model\Disponibility::RESP_OK]): ?>
                              <tr><td class="text-center">No one here !</td></tr>
                            <?php else: ?>
                              <?php foreach ($users[Application\Model\Disponibility::RESP_OK] as $user) : ?>
                                  <tr>
                                      <td class="avatar avatar-md" style="border: none; padding:2px;">
                                        <img class="img-fluid" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') :this.src = '/img/default-avatar.png';">
                                      </td>
                                      <td><?= $user->firstname ?></td>
                                      <td><?= $user->lastname ?></td>
                                      <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                                  </tr>
                              <?php endforeach; ?>
                            <?php endif ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconTwo" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-no">
                            <?php if (!$users[Application\Model\Disponibility::RESP_NO]): ?>
                              <tr><td class="text-center">No one here !</td></tr>
                            <?php else: ?>
                              <?php foreach ($users[Application\Model\Disponibility::RESP_NO] as $user) : ?>
                                  <tr>
                                      <td class="avatar avatar-md" style="border: none; padding:2px;">
                                        <img class="img-fluid" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                                      </td>
                                      <td><?= $user->firstname ?></td>
                                      <td><?= $user->lastname ?></td>
                                      <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                                  </tr>
                              <?php endforeach; ?>
                            <?php endif ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconThree" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-uncertain">
                            <?php if (!$users[Application\Model\Disponibility::RESP_UNCERTAIN]): ?>
                              <tr><td class="text-center">No one here !</td></tr>
                            <?php else: ?>
                              <?php foreach ($users[Application\Model\Disponibility::RESP_UNCERTAIN] as $user) : ?>
                                  <tr>
                                      <td class="avatar avatar-md" style="border: none; padding:2px;">
                                        <img class="img-fluid" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                                      </td>
                                      <td><?= $user->firstname ?></td>
                                      <td><?= $user->lastname ?></td>
                                      <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                                  </tr>
                              <?php endforeach; ?>
                            <?php endif ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="tab-pane" id="exampleTabsIconFour" role="tabpanel">
                      <div class="table-responsive">
                        <table class="table">
                          <tbody id="table-resp-no-answer">
                            <?php if (!$users[Application\Model\Disponibility::RESP_NO_ANSWER]): ?>
                              <tr><td class="text-center">No one here !</td></tr>
                            <?php else: ?>
                              <?php foreach ($users[Application\Model\Disponibility::RESP_NO_ANSWER] as $user) : ?>
                                  <tr>
                                      <td class="avatar avatar-md" style="border: none; padding:2px;">
                                        <img class="img-fluid" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                                      </td>
                                      <td><?= $user->firstname ?></td>
                                      <td><?= $user->lastname ?></td>
                                      <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                                  </tr>
                              <?php endforeach; ?>
                            <?php endif ?>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
      </div>
    </div>

    <!-- Right Side -->
    <div class="col-sm-4">
        <!-- Last comments -->
        <div class="panel" id="messge">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="panel-title-icon icon wb-chat-group" aria-hidden="true"></i> Comments</h3>
          </div>
          <div class="panel-body pr-0 pl-10">
            <ul class="list-group list-group-full flow-y" style="max-height: 250px">
              <?php foreach ($comments as $comment): ?>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <span class="avatar">
                      <img alt="" src="/img/avatars/<?= $comment['author']->id ?>.png" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                    </span>
                  </div>
                  <div class="media-body col-12">
                    <h5 class="list-group-item-heading mt-0 mb-5">
                      <small class="float-right">3 days ago</small>
                      <?= isset($comment['author']) ? $comment['author']->getFullName() : 'Deleted User'; ?>
                    </h5>
                    <p class="list-group-item-text"><?= nl2br($comment['comment']); ?></p>
                  </div>
                </div>
              </li>
              <?php endforeach ?>
            </ul>
          </div>
          <div class="panel-footer">
            <form>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Say something">
                <span class="input-group-btn">
                  <button class="btn btn-primary" type="button">Send</button>
                </span>
              </div>
            </form>
          </div>
        </div>
    </div>
</div>
