<div class="row" data-plugin="matchHeight" data-by-row="true">
  <div class="col-12">
    <!-- Panel Wizard Pager -->
    <div class="panel" id="statsWizard" style="min-height: calc(100% - 44px);">
      <div class="panel-heading">
        <h3 class="panel-title"></h3>
        <div class="panel-actions panel-actions-keep">
        </div>
      </div>
      <div class="panel-body">
        <div class="wizard-content">
          <div class="wizard-pane active" role="tabpanel">
            <div class="row hidden" id="slide-up-service">
              <h4 class="col-12">Service Quality</h4>
              <div class="col-12 text-center mb-10">
                <img class="avatar" src="/img/avatars/2cbab098cd318b3ef269c68d06464066.png" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
              </div>
              <div class="col-12 mb-10">
                <div class="btn-group btn-group-justified">
                  <div class="btn-group" role="group">
                    <button id="service-fault-us" data-user-id="<?= $p1 ?>" type="button" class="btn btn-danger btn-last" data-value="<?= \Application\Model\Stats::POINT_THEM ?>">
                      <span class="text-uppercase">Fault</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-danger btn-outline slide-up">
                      <span class="text-uppercase">Easy</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-warning btn-outline slide-up">
                      <span class="text-uppercase">Med.</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-success btn-outline slide-up">
                      <span class="text-uppercase">Hard</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button id="service-point-us" type="button" data-user-id="<?= $p1 ?>" class="btn btn-success btn-last" data-value="<?= \Application\Model\Stats::POINT_THEM ?>">
                      <span class="text-uppercase">Ace</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div class="row" id="slide-up-reception">
              <h4 class="col-12">Reception in play</h4>
              <div class="col-12 text-center mb-10">
                <?php foreach ($users as $user): ?>
                    <label class="btn-avatar" data-user-id="<?= $user->id ?>">
                      <img class="avatar avatar-md avatar-reception" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                    </label>
                <?php endforeach ?>
              </div>
              <div class="col-12 mb-10">
                <div class="btn-group btn-group-justified">
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-success btn-reception-quality btn-outline slide-up" disabled>
                      <span class="text-uppercase">Good</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-warning btn-reception-quality btn-outline slide-up" disabled>
                      <span class="text-uppercase">Medium</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-danger btn-reception-quality btn-outline slide-up" disabled>
                      <span class="text-uppercase">Bad</span>
                    </button>
                  </div>
                </div>
              </div>

              <h4 class="col-12">Or Service</h4>
              <div class="col-12 mb-10">
                <div class="btn-group btn-group-justified">
                  <div class="btn-group" role="group">
                    <button id="service-point-us" type="button" class="btn btn-success btn-last" data-value="<?= \Application\Model\Stats::POINT_US ?>" name="reason">
                      <span class="text-uppercase">Fault</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button id="service-point-them" type="button" class="btn btn-danger btn-last" data-value="<?= \Application\Model\Stats::POINT_THEM ?>" name="reason">
                      <span class="text-uppercase">Ace</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div class="row" id="slide-down-point" style="display: none;">
              <h4 class="col-12">Who Scores ?</h4>
              <div class="btn-group btn-group-justified">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-success btn-next" id="point-us" data-value="<?= \Application\Model\Stats::POINT_US ?>">
                    <span class="counter font-size-30"><?= $scoreUs ?></span>
                    <br>
                    <span class="text-uppercase">Us</span>
                  </button>
                </div>
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-danger btn-next" id="point-them" data-value="<?= \Application\Model\Stats::POINT_THEM ?>">
                    <span class="counter font-size-30"><?= $scoreThem ?></span>
                    <br>
                    <span class="text-uppercase">Them</span>
                  </button>
                </div>
              </div>

              <h4 class="col-12 mt-30">Dig ! <span id="confirm-dig" class="badge badge-success" style="display: none;">Saved</span></h4>
              <div class="col-12 text-center mb-10">
                <?php foreach ($users as $user): ?>
                    <label class="btn-avatar" data-user-id="<?= $user->id ?>">
                      <img class="avatar avatar-md avatar-dig" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                    </label>
                <?php endforeach ?>
              </div>
              <div class="col-12 mb-10">
                <div class="btn-group btn-group-justified">
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-success btn-dig-quality btn-outline" disabled>
                      <span class="text-uppercase">Good</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-warning btn-dig-quality btn-outline" disabled>
                      <span class="text-uppercase">Medium</span>
                    </button>
                  </div>
                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-danger btn-dig-quality btn-outline" disabled>
                      <span class="text-uppercase">Bad</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div class="wizard-pane" role="tabpanel">
            <h4>Reason ?</h4>
            <div class="btn-group btn-group-justified mb-10">
              <div class="btn-group" role="group">
                <button id="attack-us" value="<?= \Application\Model\Stats::POINT_ATTACK ?>" name="reason" class="btn btn-success btn-outline btn-next hidden">
                  <span class="counter font-size-24">Attack</span>
                  <br>
                  <span class="text-uppercase">Point</span>
                </button>
                <button id="attack-them" value="<?= \Application\Model\Stats::POINT_ATTACK ?>" name="reason" class="btn btn-success btn-outline hidden">
                  <span class="counter font-size-24">Attack</span>
                  <br>
                  <span class="text-uppercase">Point</span>
                </button>
              </div>

              <div class="btn-group" role="group">
                <button id="attack-fault-them" value="<?= \Application\Model\Stats::FAULT_ATTACK ?>" name="reason" class="btn btn-danger btn-outline hidden">
                  <span class="counter font-size-24">Attack</span>
                  <br>
                  <span class="text-uppercase">Fault</span>
                </button>
                <button id="attack-fault-us" value="<?= \Application\Model\Stats::FAULT_ATTACK ?>" name="reason" class="btn btn-danger btn-outline btn-next hidden">
                  <span class="counter font-size-24">Attack</span>
                  <br>
                  <span class="text-uppercase">Fault</span>
                </button>
              </div>
            </div>

            <div class="btn-group btn-group-justified mb-10">
              <div class="btn-group" role="group">
                <button id="block-point-us" value="<?= \Application\Model\Stats::POINT_BLOCK ?>" name="reason" class="btn btn-success btn-outline hidden btn-next">
                  <span class="counter font-size-24">Block</span>
                  <br>
                  <span class="text-uppercase">Point</span>
                </button>
                <button id="block-point-them" value="<?= \Application\Model\Stats::POINT_BLOCK ?>" name="reason" class="btn btn-success btn-outline hidden btn-next">
                  <span class="counter font-size-24">Block</span>
                  <br>
                  <span class="text-uppercase">Point</span>
                </button>
              </div>

              <div class="btn-group" role="group">
                <button id="defensive-fault" value="<?= \Application\Model\Stats::FAULT_DEFENCE ?>" name="reason" class="btn btn-danger btn-outline hidden">
                  <span class="counter font-size-24">Defence</span>
                  <br>
                  <span class="text-uppercase">Fault</span>
                </button>
              </div>
            </div>
          </div>
          <div class="wizard-pane" role="tabpanel">
            <div class="row">
                <h4>Select Player</h4>
                <div id="user-selection" class="col-12 text-center">
                    <?php foreach ($users as $user): ?>
                        <label class="btn-avatar" data-user-id="<?= $user->id ?>">
                          <img class="avatar avatar-md" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                        </label>
                    <?php endforeach ?>
                </div>

                <h4 id="table-title">Attack From ?</h4>
                <table class="table" data-delete-link="<?= $deleteLink ?>">
                  <tr>
                    <td class="court-outside inactive" width="2%" rowspan="5"></td>
                    <td class="court-outside inactive" height="40px" colspan="2"></td>
                    <!-- NET -->
                    <td rowspan="5" width="2%" class="court-net inactive out" data-target="7"></td>
                    <td class="court-outside inactive out" height="40px" colspan="2" style="border: none; color:#FFF;" data-target="8"></td>
                    <td class="court-outside inactive out" width="40px" rowspan="5" data-target="9"></td>
                  </tr>
                  <tr class="col-12">
                    <!-- attack P5 -->
                    <td height="70px" class="court-inside inactive court-border-top court-border-left court-border-right attack text-center" data-attack="5">P5</td>
                    <!-- attack P4 -->
                    <td height="70px" class="court-inside inactive court-border-top front attack text-center" data-attack="4">P4</td>
                    <!-- target P2 -->
                    <td height="70px" class="court-inside inactive court-border-top front target text-center" data-target="2">P2</td>
                    <!-- target P1 -->
                    <td height="70px" class="court-inside inactive court-border-top court-border-left court-border-right target text-center" data-target="1">P1</td>
                  </tr>
                  <tr class="col-12">
                    <!-- attack P6 -->
                    <td height="70px" class="court-inside inactive court-border-left court-border-right attack text-center" data-attack="6">P6</td>
                    <!-- attack P3 -->
                    <td height="70px" class="court-inside inactive front attack text-center" data-attack="3">P3</td>
                    <!-- target P3 -->
                    <td height="70px" class="court-inside inactive front target text-center" data-target="3">P3</td>
                    <!-- target P6 -->
                    <td height="70px" class="court-inside inactive court-border-left court-border-right target text-center" data-target="6">P6</td>
                  </tr>
                  <tr class="col-12">
                    <!-- attack P1 -->
                    <td height="70px" class="court-inside inactive court-border-bottom court-border-left court-border-right attack text-center" data-attack="1">P1</td>
                    <!-- attack P2 -->
                    <td height="70px" class="court-inside inactive court-border-bottom front attack text-center" data-attack="2">P2</td>
                    <!-- target P4 -->
                    <td height="70px" class="court-inside inactive court-border-bottom front target text-center" data-target="4">P4</td>
                    <!-- target P5 -->
                    <td height="70px" class="court-inside inactive court-border-bottom court-border-left court-border-right target text-center" data-target="5">P5</td>
                  </tr>
                  <tr>
                    <td class="court-outside inactive" height="40px" colspan="2"></td>
                    <td class="court-outside inactive out" height="40px" colspan="2" data-target="10"></td>
                  </tr>
                </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Panel Wizard Pager -->

    <form id="game-stats" method="POST" class="hidden">
        <input type="text" id="service-user" name="service-user" value=""/>
        <input type="text" id="service-quality" name="service-quality" value=""/>
        <input type="text" id="service-type" name="service-type" value="1"/>

        <input type="text" id="defence-them" name="defence-them" value="0"/>
        <input type="text" id="point-for" name="point-for" value=""/>
        <input type="text" id="reason" name="reason" value=""/>
        <input type="text" id="userId" name="userId" value=""/>
        <input type="text" id="from-zone" name="from-zone" value=""/>
        <input type="text" id="to-zone" name="to-zone" value=""/>
        <input type="text" id="score-us" name="score-us" value="<?= $scoreUs ?>"/>
        <input type="text" id="score-them" name="score-them" value="<?= $scoreThem ?>"/>
    </form>
  </div>
</div>

<?php
  $newSet   = (!$scoreUs && !$scorethem) ? 'true': 'false';
  $keyboard = ($newSet == 'true') ? 'false' : 'true';
  $backdrop = ($keyboard == 'true') ? 'dark' : 'static';
?>

<div class="modal fade" id="positions" aria-hidden="true" data-keyboard="<?= $keyboard ?>" data-backdrop="<?= $backdrop ?>" aria-labelledby="positions"
  role="dialog" tabindex="-1" data-show="<?= $newSet ?>">
  <div class="modal-dialog modal-simple">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Make Your Selection</h4>
          <?php if ($newSet == 'false'): ?>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          <?php endif ?>
        </div>
        <div class="modal-body row">
        <form id="positions-form" name="positions-form" method="POST">
          <?php if ($newSet == 'true'): ?>
            <div class="col-12 mt-10">
              <h5>Start set with</h5>
              <div class="btn-group btn-group-justified">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default btn-outline">
                    <span class="text-uppercase">
                      <div class="radio-custom radio-default">
                        <input type="radio" id="start-service" value="<?= \Application\Model\Stats::SERVICE ?>" name="start" required />
                        <label for="start-service">Service</label>
                      </div>
                    </span>
                  </button>
                </div>
                <div class="btn-group" role="group">
                 <button type="button" class="btn btn-default btn-outline">
                   <span class="text-uppercase">
                     <div class="radio-custom radio-default">
                       <input type="radio" id="start-reception" value="<?= \Application\Model\Stats::SERVICE ?>" name="start" required />
                       <label for="start-reception">Reception</label>
                     </div>
                   </span>
                 </button>
                </div>
              </div>
            </div>
          <?php endif ?>

          <div class="col-12 mt-10">
            <h5>Positions</h5>
            <table class="table">
              <tr>
                <td class="court-outside" width="40px" rowspan="5"></td>
                <td class="court-outside" height="40px" colspan="2">
                  <div class="col-8 mt-10">
                    <select name="libero" class="form-control user-select" id="libero">
                      <option selected="selected" value="" disabled>Libero</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
                <!-- NET -->
                <td rowspan="5" width="2%" class="court-net inactive out" data-target="7"></td>
              </tr>
              <tr class="col-12">
                <!-- attack P5 -->
                <td height="70px" class="court-inside court-border-top court-border-left court-border-right attack text-center" data-attack="5">
                  <div class="col-12">
                    <select class="form-control user-select"  name="p5" id="select-P5">
                      <option selected="selected" value="" disabled>P5</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
                <!-- attack P4 -->
                <td height="70px" class="court-inside court-border-top front attack text-center" data-attack="4">
                  <div class="col-12">
                    <select class="form-control user-select"  name="p4" id="select-P4">
                      <option selected="selected" value="" disabled>P4</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
              </tr>
              <tr class="col-12">
                <!-- attack P6 -->
                <td height="70px" class="court-inside court-border-left court-border-right attack text-center" data-attack="6">
                  <div class="col-12">
                    <select class="form-control user-select"  name="p6" id="select-P6">
                      <option selected="selected" value="" disabled>P6</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
                <!-- attack P3 -->
                <td height="70px" class="court-inside front attack text-center" data-attack="3">
                  <div class="col-12">
                    <select class="form-control user-select"  name="p3" id="select-P3">
                      <option selected="selected" value="" disabled>P3</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
              </tr>
              <tr class="col-12">
                <!-- attack P1 -->
                <td height="70px" class="court-inside court-border-bottom court-border-left court-border-right attack text-center" data-attack="1">
                  <div class="col-12">
                    <select class="form-control user-select"  name="p1" id="select-P1">
                      <option selected="selected" value="" disabled>P1</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
                <!-- attack P2 -->
                <td height="70px" class="court-inside court-border-bottom front attack text-center" data-attack="2">
                  <div class="col-12">
                    <select class="form-control user-select" name="p2" id="select-P2">
                      <option selected="selected" value="" disabled>P2</option>
                      <?php foreach ($users as $user): ?>
                        <option class="user-<?= $user->id ?>" value="<?= $user->id ?>"><?= $user->getFullname() ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </td>
              </tr>
              <tr>
                <td class="court-outside" height="40px" colspan="2"></td>
              </tr>
            </table>
          </div>
        </div>
        <div class="modal-footer">
          <input type="hidden" name="form-name" value="positions"/>
          <button type="submit" class="btn btn-success btn-outline" form="positions-form" value="Submit" href="#" role="button">Submit</button>
        </div>
      </div>
    </form>
  </div>
</div>