<div class="vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">
  <div class="page-content vertical-align-middle">
    <header>
      <h1 class="animation-slide-top">Sorry !</h1>
    </header>
    <p class="text-uppercase">Maybe you are trying to access an event where you are not invited or this event has been deleted.</p>

    <a class="btn btn-primary btn-round" href="/">Close</a>

    <footer class="page-copyright">
      <p>Feel free to contact us</p>
      <div class="social">
        <a class="btn btn-icon btn-pure" target="blank_" href="http://www.twitter.com/ball_eu">
      		<i class="icon fa-twitter" aria-hidden="true"></i>
	    </a>
	    <a class="btn btn-icon btn-pure" href="https://www.facebook.com/Volley-balleu-231854521008720/" target="blank_" >
	      <i class="icon fa-facebook" aria-hidden="true"></i>
	    </a>
	    <a class="btn btn-icon btn-pure" href="mailto:volleyball.eu@gmail.com">
	      <i class="icon fa-envelope" aria-hidden="true"></i>
	    </a>
      </div>
    </footer>
  </div>
</div>