
<div class="page-login-main animation-slide-right animation-duration-1">
  <div class="brand hidden-md-up">
    <img class="brand-img" src="/assets/images/logo-mail.png" alt="...">
    <h3 class="brand-text font-size-40">Volley-ball.eu</h3>
  </div>
  <h3 class="font-size-24">Sign In</h3>
  <p>Do you already have an account ?</p>

  <?php if ($this->flashMessenger()->getMessages('error')): ?>
    <div class="alert alert-alt alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      Invalid Email or Password.
    </div>
  <?php endif ?>

<?= $this->form()->openTag($signInForm); ?>
    <div class="form-group">
      <label class="sr-only" for="inputEmail">Email</label>
      <?= $this->formElement($signInForm->get('email')); ?>
    </div>
    <div class="form-group">
      <label class="sr-only" for="inputPassword">Password</label>
      <?= $this->formElement($signInForm->get('password')); ?>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Sign in</button>
    <?= $this->form()->closeTag($signInForm); ?>

    <div class="form-group clearfix">
<!--       <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
        <input type="checkbox" id="rememberMe" name="rememberMe">
        <label for="rememberMe">Remember me</label>
      </div> -->
      <p class="float-left">No account? <a href="/auth/signup<?= $group ? '?group=' . $group : ''; ?>">Sign Up</a></p>
      <a class="float-right" href="/auth/email">Forgot password?</a>
    </div>

    <footer class="page-copyright">
      <p>© 2018 Volley-ball.eu</p>
<!--     <div class="social">
      <a class="btn btn-icon btn-round social-twitter mx-5" href="javascript:void(0)">
        <i class="icon bd-twitter" aria-hidden="true"></i>
      </a>
          <a class="btn btn-icon btn-round social-facebook mx-5" href="javascript:void(0)">
        <i class="icon bd-facebook" aria-hidden="true"></i>
      </a>
          <a class="btn btn-icon btn-round social-google-plus mx-5" href="javascript:void(0)">
        <i class="icon bd-google-plus" aria-hidden="true"></i>
      </a>
    </div> -->
  </footer>
</div>