<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="header-text text-center">
            <h2>VOLLEY-BALL.EU</h2>
            <h4>S'enregistrer</h4>
            <hr>
        </div>
    </div>
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($signUpForm); ?>
            <div class="card card-plain">
                <div class="content">
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('firstname')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('lastname')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('password')); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formElement($signUpForm->get('repassword')); ?>
                    </div>
                </div>
                <div class="footer text-center">
                    <a href="/auth/signin<?= $group ? '?group=' . $group : ''; ?>">Se connecter</a> | 
                    <a href="/auth/email">Mot de passe oublié</a> | 
                    <button type="submit" class="btn btn-fill btn-danger btn-wd">Créer mon compte</button>
                </div>
            </div>
        <?= $this->form()->closeTag($signUpForm); ?>
    </div>
</div>