<div class="row">
    <div class="col-xs-12">
        <div class="card">
            <div class="card-header text-center">
                <h4 class="card-title">Groups</h4>
            </div>
            <div class="card-content">
                <div class="tab-content">
                    <div class="fresh-datatables">
                        <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th class="disabled-sorting">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($groups as $group): ?>
                                <tr>
                                    <td><?= $group->id ?></td>
                                    <td><?= $group->name ?></td>
                                    <td>
                                        <a href="#" class="btn btn-simple btn-info btn-icon like"><i class="ti-heart"></i></a>
                                        <a href="#" class="btn btn-simple btn-warning btn-icon edit"><i class="ti-pencil-alt"></i></a>
                                        <a href="#" class="btn btn-simple btn-danger btn-icon remove"><i class="ti-close"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>