<div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
  <div class="user-base card-block">
    <a class="avatar img-bordered avatar-100" href="javascript:void(0)">
      <img alt="" src="<?= $user->getAvatarPath() ?>">
    </a>
    <h4 class="user-name"><?= $user->getFullname(); ?></h4>
  </div>
  <div class="card-block"> 	
  	<table class="table">
  	  <?php foreach ($average as $type => $avg): ?>
  	     <tr>
  	       <td>
  	          <div class="row">
  		          <div class="col-3 text-left pr-0">
  		            <?= \Application\Model\Game::$literalReason[$type] ?>
  		          </div>
  		          <div class="col-6 pr-0">
  		            <div class="rating" data-score="<?= $avg ?>" data-number="5"></div>
  		          </div>
  		          <div class="col-3 font-size-24 vertical-align pull-right">
  		          	<?= $avg ?>
  		          </div>
  	          </div>
  	       </td>
  	     </tr>
         <?php if (isset($quality[$type]) && count($quality[$type]) > 4): ?>
          <tr>
            <td>     
                <div class="chart-evolution" data-score="<?= json_encode($quality[$type]) ?>"></div>
            </td>
          </tr>
        <?php endif ?>
      <?php endforeach ?>
    </table>
  </div>
</div>