<div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
  <div class="user-base card-block">
    <a class="avatar img-bordered avatar-100" href="javascript:void(0)">
      <img alt="" src="<?= $user->getAvatarPath() ?>">
    </a>
    <h4 class="user-name"><?= $user->getFullname(); ?></h4>
  </div>
  <div class="card-block"> 	
  	<table class="table">
  	  <?php foreach ($average as $type => $avg): ?>
  	     <tr>
  	       <td>
  	          <div class="row">
  		          <div class="col-3 text-left pr-0">
  		            <?= \Application\Model\Game::$literalReason[$type] ?>
  		          </div>
  		          <div class="col-6 pr-0">
  		            <div class="rating" data-score="<?= $avg ?>" data-number="5"></div>
  		          </div>
  		          <div class="col-3 font-size-24 vertical-align pull-right">
  		          	<?= $avg ?>
  		          </div>
  	          </div>
  	       </td>
  	     </tr>
  	  <?php endforeach ?>
  	</table>
  </div>
  <?php if (isset($quality[\Application\Model\Game::RECEPTION])): ?>
    <div class="card-block">
      <div id="chart-reception" data-score="<?= json_encode($quality[\Application\Model\Game::RECEPTION]) ?>"></div>
    </div>
  <?php endif ?>
  <?php if (isset($quality[\Application\Model\Game::SERVICE])): ?>
    <div class="card-block">
      <div id="chart-service" data-score="<?= json_encode($quality[\Application\Model\Game::SERVICE]) ?>"></div>
    </div>
  <?php endif ?>
  <?php if (isset($quality[\Application\Model\Game::SET]) && count($quality[\Application\Model\Game::SET]) > 4): ?>
    <div class="card-block">
      <div id="chart-set" data-score="<?= json_encode($quality[\Application\Model\Game::SET]) ?>"></div>
    </div>
  <?php endif ?>
</div>