<div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
  <div class="user-base card-block">
    <a class="avatar img-bordered avatar-100" href="javascript:void(0)">
      <img alt="" src="<?= $user->getAvatarPath() ?>">
    </a>
    <h4 class="user-name"><?= $user->getFullname(); ?></h4>
  </div>
  <div class="card-block">
    <div class="row">
      <div class="col-6">
        <div class="card card-inverse bg-success p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::POINT_ATTACK] + $counters[\Application\Model\Stats::POINT_SERVE] + $counters[\Application\Model\Stats::POINT_BLOCK] ?></span>
            <div class="counter-label text-uppercase">Points</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-success p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::POINT_ATTACK] ?></span>
            <div class="counter-label text-uppercase">Kills</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-info p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $attackAttemptCount ?></span>
            <div class="counter-label text-uppercase">Attack Attempts</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-danger p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::FAULT_ATTACK] ?></span>
            <div class="counter-label text-uppercase">Attack Faults</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card p-25 card-inverse bg-primary">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::POINT_SERVE] ?></span>
            <div class="counter-label text-uppercase">Aces</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-info p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::POINT_BLOCK] ?></span>
            <div class="counter-label text-uppercase">Blocks</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-warning p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $counters[\Application\Model\Stats::FAULT_SERVE] ?></span>
            <div class="counter-label text-uppercase">Service Faults</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card card-inverse bg-warning p-25">
          <div class="counter counter-lg">
            <span class="counter-number"><?= $digCount ?></span>
            <div class="counter-label text-uppercase">Digs</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-block">
  	<table class="table">
  	  <?php foreach ($average as $type => $avg): ?>
  	     <tr>
  	       <td>
  	          <div class="row">
  		          <div class="col-3 text-left pr-0">
  		            <?= \Application\Model\Game::$literalReason[$type] ?>
  		          </div>
  		          <div class="col-6 pr-0">
  		            <div class="rating" data-score="<?= $avg ?>" data-number="5"></div>
  		          </div>
  		          <div class="col-3 font-size-24 vertical-align pull-right">
  		          	<?= $avg ?>
  		          </div>
  	          </div>
  	       </td>
  	     </tr>
         <?php if (isset($quality[$type]) && count($quality[$type]) > 1): ?>
          <tr>
            <td>     
                <div class="chart-evolution" data-score="<?= json_encode($quality[$type]) ?>"></div>
            </td>
          </tr>
        <?php endif ?>
      <?php endforeach ?>
    </table>
  </div>
</div>