<tr>
	<td align="center" valign="top" id="m_6276084880465470621templateHeader" style="background:#e6a56a url(&quot;https://ci6.googleusercontent.com/proxy/mWJz19HvLjH2NN1J5NdPO8op324uRTuxTUc75zX2DupK2-GgsDWZl8-QZlw2IZeOJv2vCEF7byae0uU2AybMLUnFL5KnaqDb75LEFVWZkr8LHILn7yFS-ty6xEdNdPvQEjvHKNaoJ4yWsckxUMx-KLw_JOQL9a4HE5SQL-E=s0-d-e1-ft#https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg&quot;) no-repeat top/cover;background-color:#e6a56a;background-image:url(https://ci6.googleusercontent.com/proxy/mWJz19HvLjH2NN1J5NdPO8op324uRTuxTUc75zX2DupK2-GgsDWZl8-QZlw2IZeOJv2vCEF7byae0uU2AybMLUnFL5KnaqDb75LEFVWZkr8LHILn7yFS-ty6xEdNdPvQEjvHKNaoJ4yWsckxUMx-KLw_JOQL9a4HE5SQL-E=s0-d-e1-ft#https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg);background-repeat:no-repeat;background-position:top;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:80px">
		
		<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621templateContainer" style="border-collapse:collapse;max-width:600px!important">
			<tbody>
				<tr>
					<td valign="top" class="m_6276084880465470621headerContainer">
						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnTextBlock" style="min-width:100%;border-collapse:collapse">
							<tbody class="m_6276084880465470621mcnTextBlockOuter">
								<tr>
									<td valign="top" class="m_6276084880465470621mcnTextBlockInner" style="padding-top:9px">
										
										
										
										<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%" class="m_6276084880465470621mcnTextContentContainer">
											<tbody>
												<tr>
													
													<td valign="top" class="m_6276084880465470621mcnTextContent" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">
														
														<h1 style="display:block;margin:0;padding:0;color:#ffffff;font-family:Georgia;font-size:60px;font-style:normal;font-weight:normal;line-height:200%;letter-spacing:normal;text-align:center">
															<span style="font-family:arial,helvetica neue,helvetica,sans-serif">Volley-Ball.eu</span>
														</h1>

														<h2 class="m_6276084880465470621mc-toc-title" style="text-align:center;display:block;margin:0;padding:0;color:#ffffff;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
															<span style="font-family:arial,helvetica neue,helvetica,sans-serif">
																<span style="font-size:24px">Gestion d'entrainements,<br>
																&nbsp;matchs et statistiques</span>
															</span>
														</h2>

														<p style="margin:10px 0;padding:0;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">&nbsp;</p>

													</td>
												</tr>
											</tbody>
										</table>
										
										
										
									</td>
								</tr>
							</tbody>
						</table>
						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnDividerBlock" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
							<tbody class="m_6276084880465470621mcnDividerBlockOuter">
								<tr>
									<td class="m_6276084880465470621mcnDividerBlockInner" style="min-width:100%;padding:20px 18px 0px">
										<table class="m_6276084880465470621mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
											<tbody>
												<tr>
													<td>
														<span>
														</span>
													</td>
												</tr>
											</tbody>
										</table>

									</td>
								</tr>
							</tbody>
						</table>
						<table border="0" cellpadding="0" cellspacing="0" width="100%" class="m_6276084880465470621mcnButtonBlock" style="min-width:100%;border-collapse:collapse">
							<tbody class="m_6276084880465470621mcnButtonBlockOuter">
								<tr>
									<td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center" class="m_6276084880465470621mcnButtonBlockInner">
										<table border="0" cellpadding="0" cellspacing="0" class="m_6276084880465470621mcnButtonContentContainer" style="border-collapse:separate!important;border-radius:3px;background-color:#68b3c8">
											<tbody>
												<tr>
													<td align="center" valign="middle" class="m_6276084880465470621mcnButtonContent" style="font-family:Arial;font-size:16px;padding:20px">
														<a class="m_6276084880465470621mcnButton" title="Aller au site" href="http://volley-ball.eu" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://volley-ball.eu&amp;source=gmail&amp;ust=1524169316102000&amp;usg=AFQjCNHXUA5yv-kL0f_Rnf0RsoQvh0rN2w">Aller au site</a>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
		
	</td>
</tr>