<div class="col-lg-6">
<!-- Panel Wizard Form Container -->
<div class="panel" id="exampleWizardFormContainer">
  <div class="panel-heading">
    <h3 class="panel-title">Create your Group</h3>
  </div>
  <div class="panel-body">
    <!-- Steps -->
    <div class="pearls row">
      <div class="pearl current col-4">
        <div class="pearl-icon"><i class="icon wb-map" aria-hidden="true"></i></div>
        <span class="pearl-title">Group Info</span>
      </div>
      <div class="pearl col-4">
        <div class="pearl-icon"><i class="icon wb-calendar" aria-hidden="true"></i></div>
        <span class="pearl-title">Trainings</span>
      </div>
      <div class="pearl col-4">
        <div class="pearl-icon"><i class="icon wb-user-add" aria-hidden="true"></i></div>
        <span class="pearl-title">Invitations</span>
      </div>
    </div>
    <!-- End Steps -->

    <!-- Wizard Content -->
    <form id="exampleFormContainer" method="POST" action="/group/create">
      <div class="wizard-content">
        <div class="wizard-pane active" id="exampleAccountOne" role="tabpanel">
          <div class="form-group">
            <label class="form-control-label" for="inputGroupName">Name</label>
            <input type="text" class="form-control" id="inputGroupName" name="groupName" required="required" placeholder="ASC Dunois" data-groups='<?= $groupNames ?>'>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="inputGroupPlace">Place</label>
            <input type="text" class="form-control" id="inputGroupPlace" name="groupPlace" placeholder="Gymnasium Dunois">
          </div>
          <div class="form-group">
            <label class="form-control-label" for="inputGroupAddress">Address</label>
            <input type="text" class="form-control" id="inputGroupAddress" name="groupAddress" placeholder="70 rue de Dunois 75013 Paris">
          </div>
        </div>
        <div class="wizard-pane" id="exampleBillingOne" role="tabpanel">
            <div id="toClone" class="clonedInput">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">
                                Place Name
                            </label>
                            <?= $this->formElement($form->get('place[]')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Address
                            </label>
                            <?= $this->formElement($form->get('address[]')); ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">
                                Zipcode
                            </label>
                            <?= $this->formElement($form->get('zipCode[]')); ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">
                                City
                            </label>
                            <?= $this->formElement($form->get('city[]')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Training Day
                            </label>
                            <?= $this->formElement($form->get('eventDay[]')); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Start Time
                            </label>
                            <?= $this->formElement($form->get('time[]')); ?>
                        </div>
                    </div>
                </div>
                <hr>
            </div>
            <div id="cloneTarget"></div>
            <div class="row">
                <div class="col-12 text-center">
                    <button type="button" class="btn btn-primary clone">Add more</a>
                </div>
            </div>
        </div>
        <div class="wizard-pane" id="exampleGettingOne" role="tabpanel">
            <div class="row text-center">
                <div class="col-12">
                    <div class="form-group">
                        <label class="control-label">
                            Invitez des joueurs
                        </label>
                        <?= $this->formElement($form->get('emails')); ?>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </form>
    <!-- Wizard Content -->
  </div>
</div>
<!-- End Panel Wizard Form Container -->
</div>