<div class="col-lg-6">
<!-- Panel Wizard Form Container -->
<div class="panel">
  <div class="panel-heading">
  </div>
  <div class="panel-body">
    <!-- Wizard Content -->
    <form id="exampleFormContainer" method="POST" action="/group/create">
      <div class="wizard-content">
        <h4 class="panel-title">Create your Group</h4>
        <div>
          <div class="form-group">
            <label class="form-control-label" for="inputGroupName">Name</label>
            <input type="text" class="form-control" id="inputGroupName" name="groupName" required="required" placeholder="ASC Dunois" data-groups='<?= $groupNames ?>'>
            <div class="error hidden">
                <div class="alert alert-alt alert-danger alert-dismissible mt-20" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                  Name already taken
                </div>
            </div>
          </div>
        </div>
        <hr>
        <h4 class="panel-title">Set Up Trainnings (optional)</h4>
        <div>
            <div id="toClone" class="clonedInput mt-20">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">
                                Place Name
                            </label>
                            <input type="text" class="form-control" name="place[]" placeholder="Gymnasium Dunois">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">
                                Full Address
                            </label>
                            <input type="text" class="form-control" name="address[]" placeholder="70 rue de Dunois, 75013 Paris">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label class="control-label">
                                Training Day
                            </label>
                            <select class="form-control" name="eventDay[]">
                              <option value="0" selected disabled>Select Day</option>
                              <option value="monday">Monday</option>
                              <option value="tuesday">Tuesday</option>
                              <option value="wednesday">Wednesday</option>
                              <option value="thursday">Thursday</option>
                              <option value="friday">Friday</option>
                              <option value="saturday">Saturday</option>
                              <option value="sunday">Sunday</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label">
                                Start Time
                            </label>
                            <input type="text" name="time[]" class="form-control" id="inputTime" data-plugin="formatter" data-pattern="[[99]]:[[99]]" placeholder="20:00">
                        </div>
                    </div>
                </div>
            </div>
            <div id="cloneTarget"></div>
            <div class="row">
                <div class="col-12 text-center">
                    <button type="button" class="btn btn-primary btn-outline clone float-right">Add more</a>
                </div>
            </div>
        </div>
        <hr>
        <h4 class="panel-title">Invite People (optional)</h4>
        <div>
            <label class="control-label">
                Add Emails
            </label>
            <input type="text" class="form-control" id="inputTokenfieldEvents" data-tokens=""
        />
        </div>
        <hr>
        <div>
            <button type="submit" class="btn btn-success ladda-button float-right" data-timeout="15000" id="submit-form" data-style="zoom-in" data-plugin="ladda">
                <span class="ladda-label">Submit</span>
                <span class="ladda-spinner"></span>
                <div class="ladda-progress" style="width: 0px;"></div>
            </button>
        </div>
      </div>
    </form>
    <!-- Wizard Content -->
  </div>
</div>
<!-- End Panel Wizard Form Container -->
</div>