<div class="page-content container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
              <div class="user-info card card-shadow text-center mb-0">
                <div class="user-base card-block">
                  <a class="avatar img-bordered avatar-100" href="javascript:void(0)">
                    <img alt="" src="<?= $group->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                  </a>
                  <h4 class="user-name"><?= $group->name; ?></h4>
                </div>
                <div class="card-block">
                  <?php $form->prepare(); // The correct enctype is set here ?>
                  <?= $this->form()->openTag($form); ?>
                    <div class="form-group">
                      <input type="text" class="form-control" name="name" placeholder="Group Name"
                        autocomplete="off" value="<?= $group->name ?>" />
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" class="form-control" name="zipcode" placeholder="Zipcode"
                          autocomplete="off" value="<?= $group->id ?>"/>
                      </div>
                      <div class="form-group col-md-6">
                        <input type="text" class="form-control" name="city" placeholder="City"
                          autocomplete="off" value="<?= $group->id ?>"/>
                      </div>
                    </div>
                    <div class="form-element">
                        <label>Change your image</label>
                        <?php $fileElement = $form->get('image-file'); ?>
                        <?= $this->formFile($fileElement); ?>
                    </div>
                    <div class="form-group mt-10 float-right">
                      <input type="submit" class="btn btn-primary" name="submit" value="Submit">
                    </div>
                  <?= $this->form()->closeTag(); ?>
                </div>
              </div>
            </div>
        </div>
        <div class="col-md-4">
            <!-- Card -->
            <div class="card card-block p-30 bg-green-600">
                <div class="card-watermark darker font-size-80 m-15"><i class="icon wb-users" aria-hidden="true"></i></div>
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">42</span>
                        <span class="counter-number-related text-capitalize">People</span>
                    </div>
                    <div class="counter-label text-capitalize">in group</div>
                </div>
            </div>
            <!-- End Card -->
            <!-- Card -->
            <div class="card card-block p-30 bg-red-600">
                <div class="card-watermark darker font-size-80 m-15"><i class="icon wb-calendar" aria-hidden="true"></i></div>
                <div class="counter counter-md counter-inverse text-left">
                    <div class="counter-number-group">
                        <span class="counter-number">142</span>
                        <span class="counter-number-related text-capitalize">Events</span>
                    </div>
                    <div class="counter-label text-capitalize">in room</div>
                </div>
            </div>
            <!-- End Card -->

            <div class="card card-shadow">
              <div class="card-header card-header-transparent">
                <h4 class="card-title">
                  Trainings
                </h4>
              </div>
              <div class="card-block">
                <div class="table-responsive">
                  <table class="table">
                    <tbody id="table-resp-ok">
                      <?php if (!$trainings): ?>
                        <tr><td class="text-center">No training here !</td></tr>
                      <?php else: ?>
                        <?php foreach ($trainings as $training) : ?>
                            <tr>
                                <td><?= $training->name ?></td>
                                <td><?= $training->eventDay ?></td>
                                <td><?= $training->time ?></td>
                                <td><a href="#"><i class="icon wb-trash "></i></a></td>
                            </tr>
                        <?php endforeach; ?>
                      <?php endif ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
        <div class="col-md-5">
          <div class="card card-shadow">
            <div class="card-header card-header-transparent">
              <h4 class="card-title">
                <i class="icon wb-users"></i> Your team
              </h4>
            </div>
            <div class="card-block">
              <div class="table-responsive">
                <table class="table">
                  <tbody id="table-resp-ok">
                    <?php if (!$users): ?>
                      <tr><td class="text-center">No one here !</td></tr>
                    <?php else: ?>
                      <?php foreach ($users as $user) : ?>
                          <tr>
                              <td class="avatar avatar-md" style="border: none; padding:2px;">
                                <img class="img-fluid" src="<?= $user->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                              </td>
                              <td><?= $user->firstname ?></td>
                              <td><?= $user->lastname ?></td>
                              <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                          </tr>
                      <?php endforeach; ?>
                    <?php endif ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

<div class="calendar-container">
    <div id="calendar" data-groupId="<?= $group->id ?>"></div>
    <?= $this->partial('partial/event-detail-side.phtml') ?>
    <?= $this->partial('partial/add-event.phtml') ?>
</div>