  <div class="row">

    <div class="col-md-6 col-12">
      <div class="row">
        <div class="col-12">
          <div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
            <div class="user-base card-block">
              <span class="avatar img-bordered avatar-100" href="javascript:void(0)">
                <img src="<?= $group->getAvatarPath() ?>">
              </span>
              <h4 class="user-name"><?= $group->name; ?></h4>
            </div>
          </div>
        </div>

        <div class="col-4">
          <div class="card card-shadow card-completed-options">
            <div class="card-block p-30">
              <div class="row">
                <div class="counter col-12 text-center blue-grey-700">
                  <div class="counter-label mt-10">Events
                  </div>
                  <div class="counter-number font-size-40 mt-10 red-600">
                    <?= $eventsCount ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-4">
          <div class="card card-shadow card-completed-options">
            <div class="card-block p-30">
              <div class="row">
                <div class="counter col-12 text-center blue-grey-700">
                  <div class="counter-label mt-10">People
                  </div>
                  <div class="counter-number font-size-40 mt-10 green-600">
                    <?= count($users) ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-4">
          <div class="card card-shadow card-completed-options">
            <div class="card-block p-30">
              <div class="row">
                <div class="counter col-12 text-center blue-grey-700">
                  <div class="counter-label mt-10">Matchs
                  </div>
                  <div class="counter-number font-size-40 mt-10 blue-600">
                   <?= $matchCount ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12">
          <div id="recentActivityWidget" class="card card-shadow card-lg pb-20">
            <div class="card-header card-header-transparent pb-10">
              <h5 class="card-title">
                Team
              </h5>
            </div>
            <div class="card-block">
              <div class="table-responsive">
                <table class="table">
                  <tbody id="table-resp-ok">
                    <?php if (!$users): ?>
                      <tr><td class="text-center">No one here !</td></tr>
                    <?php else: ?>
                      <?php foreach ($users as $user) : ?>
                          <tr>
                              <td>
                                <div class="avatar avatar-md">
                                  <img class="img-fluid" src="<?= $user->getAvatarPath() ?>">
                                </div>
                              </td>
                              <td><?= $user->getFullname() ?></td>
                              <td><span class="badge badge-outline badge-info float-right">Outside Hitter</span></td>
                              <?php if ($isAdmin): ?>
                                <td>
                                  <a href="#" class='btn btn-danger btn-xs btn-outline float-right'>  <i class="icon wb-trash"></i>
                                  </a>
                                  <a href="#" class='btn btn-info btn-xs btn-outline float-right mr-5'>
                                    <i class="icon wb-pencil"></i></a>
                                </td>
                              <?php endif ?>
                          </tr>
                      <?php endforeach; ?>
                    <?php endif ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="col-md-6 col-12">
      <div class="row">
        <div class="col-12 col-md-6">
          <div class="card card-shadow card-completed-options">
            <div class="card-block p-30">
              <div class="row">
                <div class="col-6">
                  <div class="counter text-left blue-grey-700">
                    <div class="counter-label mt-10">Victory
                    </div>
                    <div class="counter-number font-size-40 mt-10">
                      <?= $winCount ?>
                    </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="pie-progress pie-progress-sm" data-plugin="pieProgress" data-valuemax="100"
                    data-barcolor="#57c7d4" data-size="100" data-barsize="10"
                    data-goal="<?= $winPercent ?>" aria-valuenow="<?= $winPercent ?>" role="progressbar">
                    <span class="pie-progress-number blue-grey-700 font-size-20">
                      <?= $winPercent ?>%
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6">
          <div class="card card-shadow card-completed-options">
            <div class="card-block p-30">
              <div class="row">
                <div class="col-6">
                  <div class="counter text-left blue-grey-700">
                    <div class="counter-label mt-10">Defeat
                    </div>
                    <div class="counter-number font-size-40 mt-10">
                      <?= $loseCount ?>
                    </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="pie-progress pie-progress-sm" data-plugin="pieProgress" data-valuemax="100"
                    data-barcolor="#f96868" data-size="100" data-barsize="10"
                    data-goal="<?= $losePercent ?>" aria-valuenow="<?= $losePercent ?>" role="progressbar">
                    <span class="pie-progress-number blue-grey-700 font-size-20">
                      <?= $losePercent ?>%
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12">
          <div id="recentActivityWidget" class="card card-shadow card-lg pb-20">
            <div class="card-header card-header-transparent pb-10">
              <h5 class="card-title">
                LAST GAMES
              </h5>
            </div>
            <ul class="timeline timeline-icon">
              <?php foreach ($games as $game): ?>
                <li class="timeline-reverse timeline-item">
                  <div class="timeline-content-wrap">
                    <div class="timeline-dot <?= $game->victory ? 'bg-green-600' : 'bg-red-600' ?>">
                      <i class="icon <?= $game->victory ? 'wb-check' : 'wb-close' ?>" aria-hidden="true"></i>
                    </div>
                    <div class="timeline-content">
                      <div class="title">
                        <span class="authors"><a href="/event/detail/<?= $game->id ?>"><?= $game->name ?></a></span> <span class="float-right font-size-30 <?= $game->victory ? 'text-success' : 'text-danger' ?>"><?= $game->score ?></span>
                      </div>
                      <div class="metas">
                        <?php if ($game->sets): ?>
                              <?= implode(' | ', $game->sets) ?>
                        <?php endif ?>
                      </div>
                      <ul class="members">
                        <?php if (isset($present[$game->id])): ?>
                        <?php foreach ($present[$game->id] as $userId): ?>
                          <li>
                            <img class="avatar avatar-sm" src="<?= $users[$userId]->getAvatarPath() ?>" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
                          </li>
                        <?php endforeach ?>
                        <?php endif ?>
                      </ul>
                    </div>
                  </div>
                </li>
              <?php endforeach ?>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- End Personal -->
  </div>

  <div class="modal fade" id="editGroup" aria-hidden="true" aria-labelledby="editGroup"
  role="dialog" tabindex="-1" data-show="false">
    <div class="modal-dialog modal-simple">
      <div class="modal-content">
        <div class="modal-body">
          <div class="col-12 text-center mb-20">
            <span class="avatar img-bordered avatar-100" href="javascript:void(0)">
              <img alt="" src="<?= $group->getAvatarPath() ?>">
            </span>
          </div>
          <?php $form->prepare(); // The correct enctype is set here ?>
          <?= $this->form()->openTag($form); ?>
            <div class="form-group">
              <input type="text" class="form-control" name="name" placeholder="Group Name"
                autocomplete="off" value="<?= $group->name ?>" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="place" autocomplete="off" <?= $group->id ? 'value="' . $group->id . '"' : 'placeholder="Place"' ?>value="<?= $group->id ?>"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="address" autocomplete="off" <?= $group->id ? 'value="' . $group->id . '"' : 'placeholder="Address"' ?>value="<?= $group->id ?>"/>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <input type="text" class="form-control" name="zipcode" autocomplete="off" <?= $group->id ? 'value="' . $group->id . '"' : 'placeholder="Zipcode"' ?>value="<?= $group->id ?>"/>
              </div>
              <div class="form-group col-md-6">
                <input type="text" class="form-control" name="city" autocomplete="off" <?= $group->id ? 'value="' . $group->id . '"' : 'placeholder="City"' ?>value="<?= $group->id ?>"/>
              </div>
            </div>
            <div class="form-element">
                <label>Change Thumbnail</label>
                <?php $fileElement = $form->get('image-file'); ?>
                <?= $this->formFile($fileElement); ?>
            </div>
            <div class="form-group mt-10 float-right">
              <input type="submit" class="btn btn-primary" name="submit" value="Submit">
            </div>
          <?= $this->form()->closeTag(); ?>
        </div>
      </div>
    </div>
  </div>