<!doctype html>
<html lang="fr">
    <head>
    	<meta charset="utf-8" />
    	<!-- <link rel="apple-touch-icon" sizes="76x76" href="/vendor/theme//vendor/landing/assets/img/apple-icon.png"> -->
    	<link rel="icon" type="image/png" href="/img/favicon.png">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    	<title>Volley-ball.eu</title>

    	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />

        <link href="/vendor/theme/assets/css/bootstrap.min.css" rel="stylesheet" />

        <link href="/vendor/landing/assets/css/landing-page.css" rel="stylesheet"/>

        <!--  Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
        <link href="/vendor/landing/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />

    </head>
    <body class="landing-page landing-page1">
        <div class="wrapper">
            <div class="parallax filter-gradient blue" data-color="blue">
                <div class="parallax-background">
                    <img class="parallax-background-image" src="/img/volley-back.jpg">
                </div>
                <div class= "container">
                    <div class="row">
                        <div class="col-md-5 hidden-xs">
                            <div class="parallax-image">
                                <img class="phone" src="/img/iphone.png" style="margin-top: 20px"/>
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-1">
                            <div class="description">
                                <h2>VOLLEY-BALL.EU</h2>
                                <br>
                                <h5>Une gestion simple de votre groupe, de vos entrainements et matches.</h5>
                            </div>
                            <div class="buttons">
                                <a href="/auth/signin" class="btn btn-fill btn-neutral">
                                    Se connecter
                                </a>
                                <a href="/auth/signup" class="btn btn-fill btn-neutral">
                                    S'engegistrer
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section section-features">
                <div class="container">
                    <h4 class="header-text text-center">Quelques fonctionalités</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-users"></i>
                                </div>
                                <div class="text">
                                    <h4>Créez et Gérez votre groupe</h4>
                                    <p>Quelques minutes suffiront pour créer un groupe et le partager à vos joueurs.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-gym"></i>
                                </div>
                                <h4>Créez vos entrainements</h4>
                                <p>Des évènements récurents avec une création automatique chaque semaine. Décidez quand les rendre inactif ou quand les activer.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-cup"></i>
                                </div>
                                <h4>Créez vos matchs</h4>
                                <p>Un nom, une addresse et une date suffisent à créer un évènement ponctuel.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-note2"></i>
                                </div>
                                <h4>Toujours être au courant</h4>
                                <p>A tout moment vous saurez quel est votre effectif pour la prochaine séance et ainsi orienter votre entrainement.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-bell"></i>
                                </div>
                                <h4>Notifications simples</h4>
                                <p>Pour chaque création d'évènement les membres du groupe seront notifiés par email et pourront, en un seul clic, donner leur disponibilité.</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-blue">
                                <div class="icon">
                                    <i class="pe-7s-graph1"></i>
                                </div>
                                <h4>Statistique live des matchs</h4>
                                <p>Prenez des statistiques de votre équipe pendant un match de façon extrèmement simple, permettant un vue en live du score et des statistiques.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-presentation">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="description">
                                <h4 class="header-text">Un Design Responsive</h4>
                                <p>Cet outil a été développé pour être utilisable sur ordinateur de bureau, tablette ou smartphone.
                                <br>
                                <br>
                                Où que vous soyez, vous pourrez utiliser très facilement notre site !</p>
                            </div>
                        </div>
                        <div class="col-md-5 col-md-offset-1 hidden-xs">
                            <img src="/img/devices.png"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-demo">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <iframe width="100%" height="315px" src="https://www.youtube.com/embed/zPmDC1x5Qdc" frameborder="0" allowfullscreen></iframe>
                        </div>
                        <div class="col-md-5 col-md-offset-1">
                            <h4 class="header-text">Démonstration ?</h4>
                            <p>
                                Si vous n'êtes pas encore tout à fait convaincu, voici une vidéo prouvant la simplicité et la rapidité d'utilisation du site.
                            </p>
                            <a href="https://www.youtube.com/embed/zPmDC1x5Qdc" id="Demo3" class="btn btn-fill btn-info" data-button="info">Youtube</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section section-no-padding">
                <div class="parallax filter-gradient blue" data-color="blue">
                    <div class="parallax-background">
                        <img class ="parallax-background-image" src="/img/volley-back.jpg"/>
                    </div>
                    <div class="info">
                        <h1>N'attendez plus, essayez !</h1>
                        <a href="/auth/signin" class="btn btn-neutral btn-lg btn-fill">Se connecter</a>
                        <a href="/auth/signup" class="btn btn-neutral btn-lg btn-fill">S'enregistrer</a>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <div class="copyright">
                        &copy; 2017 YuCkY, made with love
                    </div>
                </div>
            </footer>
        </div>

    </body>
    <script src="/vendor/theme/assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/perfect-scrollbar.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/vendor/landing/assets/js/awesome-landing-page.js" type="text/javascript"></script>
</html>
