<!doctype html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <!-- <link rel="apple-touch-icon" sizes="76x76" href="/vendor/theme/assets/img/apple-icon.png"> -->
        <link rel="icon" type="image/png" href="/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Volley-ball.eu</title>

        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />


        <!-- Bootstrap core CSS     -->
        <link href="/vendor/theme/assets/css/bootstrap.min.css" rel="stylesheet" />

        <link href="/vendor/cards/assets/css/hipster_cards.css" rel="stylesheet"/>

        <!--  Paper Dashboard core CSS    -->
        <link href="/vendor/theme/assets/css/paper-dashboard.css?v=<?= $this->vCss ?>" rel="stylesheet"/>

        <link href="/css/style.css?v=<?= $this->vCss ?>" rel="stylesheet"/>

        <!--  Fonts and icons     -->
        <link href="/vendor/fontawesome/fontawesome-all.min.css" rel="stylesheet">

        <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
        <link href="/vendor/theme/assets/css/themify-icons.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet">
    </head>

    <body class="sidebar-mini">
        <div class="wrapper">
            <div class="sidebar" data-background-color="brown" data-active-color="info">
                <div class="logo">
                    <a href="/" class="simple-text logo-mini">
                        VB
                    </a>
                    <a href="/" class="simple-text logo-normal">
                        Volley-ball.eu
                    </a>
                </div>
                <?= $this->partial('partial/sidebar.phtml') ?>
            </div>

            <div class="main-panel">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-minimize">
                            <button id="minimizeSidebar" class="btn btn-fill btn-icon"><i class="ti-more-alt"></i></button>
                        </div>
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar bar1"></span>
                                <span class="icon-bar bar2"></span>
                                <span class="icon-bar bar3"></span>
                            </button>

                            <a class="navbar-brand" href="/">
                                <i class='fa fa-home'></i> Volley-ball.eu
                            </a>
                        </div>
                        <div class="collapse navbar-collapse">
                            <!-- <form class="navbar-form navbar-left navbar-search-form" role="search">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                    <input type="text" value="" class="form-control" placeholder="Search...">
                                </div>
                            </form> -->

                            <!-- <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle btn-rotate" data-toggle="dropdown">
                                        <i class="ti-bell"></i>
                                        <span class="notification">5</span>
                                        <p class="hidden-md hidden-lg">
                                            Notifications
                                            <b class="caret"></b>
                                        </p>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#not1">Notification 1</a></li>
                                        <li><a href="#not2">Notification 2</a></li>
                                        <li><a href="#not3">Notification 3</a></li>
                                        <li><a href="#not4">Notification 4</a></li>
                                        <li><a href="#another">Another notification</a></li>
                                    </ul>
                                </li>
                            </ul> -->
                        </div>
                    </div>
                </nav>

                <div class="content">
                    <div class="container-fluid">
                        <?= $this->content ?>
                    </div>
                </div>
                <footer class="footer hidden-xs">
                    <div class="copyright pull-right">
                        &copy; <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by YuCkY
                    </div>
                </footer>
            </div>
        </div>
        <?php if ($success = $this->flashMessenger()->getMessages('success')) :  ?>
            <div id='notification' data-type='success' data-message="<?= current($success) ?>"></div>
        <?php elseif ($error = $this->flashMessenger()->getMessages('error')): ?>
            <div id='notification' data-type='danger' data-message="<?= current($error) ?>"></div>
        <?php endif; ?>
    </body>

    <!--   Core JS Files. Extra: TouchPunch for touch library inside jquery-ui.min.js   -->
    <script src="/vendor/theme/assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/perfect-scrollbar.min.js" type="text/javascript"></script>
    <script src="/vendor/theme/assets/js/bootstrap.min.js" type="text/javascript"></script>
    
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
    <script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>


    <!--  Forms Validations Plugin -->
    <script src="/vendor/theme/assets/js/jquery.validate.min.js"></script>

    <!-- Promise Library for SweetAlert2 working on IE -->
    <script src="/vendor/theme/assets/js/es6-promise-auto.min.js"></script>

    <!--  Plugin for Date Time Picker and Full Calendar Plugin-->
    <script src="/vendor/theme/assets/js/moment-with-locales-min.js"></script>

    <!--  Date Time Picker Plugin is included in this js file -->
    <script src="/vendor/theme/assets/js/bootstrap-datetimepicker.js"></script>

    <!--  Select Picker Plugin -->
    <script src="/vendor/theme/assets/js/bootstrap-selectpicker.js"></script>

    <!--  Switch and Tags Input Plugins -->
    <script src="/vendor/theme/assets/js/bootstrap-switch-tags.js"></script>

    <!-- Circle Percentage-chart -->
    <script src="/vendor/theme/assets/js/jquery.easypiechart.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/vendor/theme/assets/js/bootstrap-notify.js"></script>

    <!-- Sweet Alert 2 plugin -->
    <script src="/vendor/theme/assets/js/sweetalert2.js"></script>

    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD9Ni7o-yS1BMooPWV-wz4uB50hTkHsQSI"></script>

    <!-- Wizard Plugin    -->
    <script src="/vendor/theme/assets/js/jquery.bootstrap.wizard.min.js"></script>

    <!--  Bootstrap Table Plugin    -->
    <script src="/vendor/theme/assets/js/bootstrap-table.js"></script>

    <!--  Plugin for DataTables.net  -->
    <script src="/vendor/theme/assets/js/jquery.datatables.js"></script>

    <!--  Full Calendar Plugin    -->
    <script src="/vendor/theme/assets/js/fullcalendar.min.js"></script>

    <!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
    <script src="/vendor/theme/assets/js/paper-dashboard.js"></script>

    <!-- Wizard Plugin    -->
    <script src="/vendor/theme/assets/js/jquery.bootstrap.wizard.min.js"></script>

    <!-- Paper Dashboard PRO DEMO methods, don't include it in your project! -->
    <script src="/js/script.js?v=<?= $this->vJs ?>"></script>

    <script src="/vendor/clipboard/clipboard.min.js"/></script>

    <script src="/vendor/fontawesome/fontawesome-all.min.js"/></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"/></script>
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
        <script>
          var email = '<?= $user->email ?>';
          var OneSignal = window.OneSignal || [];
          OneSignal.push(function() {
            OneSignal.init({
              appId: "c4d58564-1405-407d-a462-a0019ceffda7",
              autoRegister: false,
              notifyButton: {
                enable: true,
              }
            });
            OneSignal.sendTags({
                email: email,
            });
          });
        </script>

    <script type="text/javascript">
        $(document).ready(function(){
            demo.initStatsDashboard();
            demo.initCirclePercentage();
            demo.initChartDisponibilities();
            demo.initFullCalendar();
            demo.initFormExtendedDatetimepickers();
            demo.initSwitchers();
            demo.showNotification();
            demo.initHighcharts();
            demo.initLiveScore();
            // demo.initMultipleCharts();
            demo.initWizard();
            demo.initCounterButton();
            demo.initSubmitButton();
            demo.initClipboard();
            demo.initClone();
            // demo.initStatsBtns();
        });
    </script>

</html>
