<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Volley-ball manage your team, trainings, matchs and statistics">
    <meta name="author" content="Benoit Duval">
    
    <title>Volley-ball.eu | Manage your team, trainings, matchs and statistics</title>

    <link rel="icon" type="image/png" href="/img/favicon.png">

    <?= $this->assets()->render('css', $this->assetsBundle) ?>

    <!--[if lt IE 9]>
    <script src="/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    
    <!--[if lt IE 10]>
    <script src="/global/vendor/media-match/media.match.min.js"></script>
    <script src="/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    
    <!-- Scripts -->
    <script src="/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
  </head>
  <body class="animsition site-menubar-fold site-menubar-keep">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <?= $this->partial('partial/navbar.phtml') ?>
    <?= $this->partial('partial/sidebar.phtml') ?>

    <!-- Page -->
    <div class="page">
        <div class="page-content container-fluid">
            <?= $this->content ?>
        </div>
    </div>

    <!-- Site Action -->
<!--     <div class="site-action" data-plugin="actionBtn">
      <button type="button" class="site-action-toggle btn-raised btn btn-success btn-floating">
        <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
        <i class="back-icon wb-trash animation-scale-up" aria-hidden="true"></i>
      </button>
    </div> -->
    <!-- End Site Action -->


    <!-- Footer -->
    <footer class="site-footer">
      <div class="site-footer-legal">© 2018 <a href="http://volley-ball.eu">Volley-ball.eu</a></div>
      <div class="site-footer-right">
        Crafted with <i class="red-600 wb wb-heart"></i> by YuCkY
      </div>
    </footer>

    <?= $this->assets()->render('js', $this->assetsBundle) ?>

  </body>
</html>
