
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Volley-ball.eu | Manage your team, games, statistics">
    <meta name="author" content="">
    
    <title>Volley-ball.eu | Manage your team, games, statistics</title>
    
    <link rel="icon" type="image/png" href="/img/favicon.png">
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="/global/css/bootstrap.min.css">
    <link rel="stylesheet" href="/global/css/bootstrap-extend.min.css">
    <link rel="stylesheet" href="/assets/css/site.min.css">
    <link rel="stylesheet" href="/css/custom.css">
    
    <!-- Plugins -->
    <link rel="stylesheet" href="/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="/global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="/global/vendor/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="/global/vendor/bootstrap-datepicker/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/global/vendor/bootstrap-touchspin/bootstrap-touchspin.css">
    <link rel="stylesheet" href="/global/vendor/jquery-selective/jquery-selective.css">
    <link rel="stylesheet" href="/assets/examples/css/apps/calendar.css">
    <link rel="stylesheet" href="/assets/examples/css/forms/masks.css">
    <link rel="stylesheet" href="/global/vendor/bootstrap-select/bootstrap-select.css">
    <link rel="stylesheet" href="/global/vendor/bootstrap-table/bootstrap-table.css">
    <link rel="stylesheet" href="/global/vendor/ladda/ladda.css">
    <link rel="stylesheet" href="/assets/examples/css/uikit/buttons.css">

    <!-- Fonts -->
    <link rel="stylesheet" href="/global/fonts/web-icons/web-icons.min.css">
    <link rel="stylesheet" href="/global/fonts/brand-icons/brand-icons.min.css">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
    
    <!--[if lt IE 9]>
    <script src="/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    
    <!--[if lt IE 10]>
    <script src="/global/vendor/media-match/media.match.min.js"></script>
    <script src="/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    
    <!-- Scripts -->
    <script src="/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
  </head>
  <body class="animsition site-menubar-fold site-menubar-keep app-calendar page-aside-left">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <?= $this->partial('partial/navbar.phtml') ?>
    <?= $this->partial('partial/sidebar.phtml') ?>

    <!-- Page -->
    <div class="page">

      <?= $this->partial('partial/page-aside.phtml') ?>

      <div class="page-main">
        <?= $this->content ?>
      </div>
    </div>

    <!-- Site Action -->
<!--     <div class="site-action" data-plugin="actionBtn">
      <button type="button" class="site-action-toggle btn-raised btn btn-success btn-floating">
        <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
        <i class="back-icon wb-trash animation-scale-up" aria-hidden="true"></i>
      </button>
    </div> -->
    <!-- End Site Action -->


    <!-- Footer -->
    <footer class="site-footer">
      <div class="site-footer-legal">© 2018 <a href="http://volley-ball.eu">Volley-ball.eu</a></div>
      <div class="site-footer-right">
        Crafted with <i class="red-600 wb wb-heart"></i> by YuCkY
      </div>
    </footer>
    <!-- Core  -->
    <script src="/global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
    <script src="/global/vendor/jquery/jquery.js"></script>
    <script src="/global/vendor/popper-js/umd/popper.min.js"></script>
    <script src="/global/vendor/bootstrap/bootstrap.js"></script>
    <script src="/global/vendor/animsition/animsition.js"></script>
    <script src="/global/vendor/mousewheel/jquery.mousewheel.js"></script>
    <script src="/global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
    <script src="/global/vendor/asscrollable/jquery-asScrollable.js"></script>
    <script src="/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
    
    <!-- Plugins -->
    <script src="/global/vendor/switchery/switchery.js"></script>
    <script src="/global/vendor/intro-js/intro.js"></script>
    <script src="/global/vendor/screenfull/screenfull.js"></script>
    <script src="/global/vendor/slidepanel/jquery-slidePanel.js"></script>
    <script src="/global/vendor/jquery-ui/jquery-ui.min.js"></script>
    <script src="/global/vendor/moment/moment.min.js"></script>
    <script src="/global/vendor/fullcalendar/fullcalendar.js"></script>
    <script src="/global/vendor/jquery-selective/jquery-selective.min.js"></script>
    <script src="/global/vendor/bootstrap-datepicker/bootstrap-datepicker.js"></script>
    <script src="/global/vendor/bootstrap-touchspin/bootstrap-touchspin.min.js"></script>
    <script src="/global/vendor/bootbox/bootbox.js"></script>
    <script src="/global/vendor/formatter/jquery.formatter.js"></script>
    <script src="/global/vendor/bootstrap-select/bootstrap-select.js"></script>
    <script src="/global/vendor/matchheight/jquery.matchHeight-min.js"></script>
    <script src="/global/vendor/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="/global/vendor/bootstrap-table/extensions/mobile/bootstrap-table-mobile.js"></script>

    <!-- Scripts -->
    <script src="/global/js/Component.js"></script>
    <script src="/global/js/Plugin.js"></script>
    <script src="/global/js/Base.js"></script>
    <script src="/global/js/Config.js"></script>
    <script src="/global/js/Plugin/loading-button.js"></script>
    <script src="/global/js/Plugin/more-button.js"></script>
    <script src="/global/js/Plugin/ladda.js"></script>
    
    <script src="/assets/js/Section/Menubar.js"></script>
    <script src="/assets/js/Section/GridMenu.js"></script>
    <script src="/assets/js/Section/Sidebar.js"></script>
    <script src="/assets/js/Section/PageAside.js"></script>
    <script src="/assets/js/Plugin/menu.js"></script>
    
    <script src="/global/js/config/colors.js"></script>
    <script src="/assets/js/config/tour.js"></script>
    <script>Config.set('assets', '/assets');</script>
    
    <!-- Page -->
    <script src="/assets/js/Site.js"></script>
    <script src="/global/js/Plugin/asscrollable.js"></script>
    <script src="/global/js/Plugin/slidepanel.js"></script>
    <script src="/global/js/Plugin/switchery.js"></script>
    <script src="/global/js/Plugin/bootstrap-touchspin.js"></script>
    <script src="/global/js/Plugin/bootstrap-datepicker.js"></script>
    <script src="/global/js/Plugin/material.js"></script>
    <script src="/global/js/Plugin/action-btn.js"></script>
    <script src="/global/js/Plugin/editlist.js"></script>
    <script src="/global/js/Plugin/bootbox.js"></script>
    <script src="/global/js/Plugin/formatter.js"></script>
    <script src="/global/js/Plugin/responsive-tabs.js"></script>
    <script src="/global/js/Plugin/closeable-tabs.js"></script>
    <script src="/global/js/Plugin/tabs.js"></script>
    <script src="/assets/js/Site.js"></script>
    <script src="/assets/js/App/Calendar.js"></script>


        <script src="/assets/examples/js/apps/calendar.js"></script>
  </body>
</html>
