<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-bookmark ribbon-warning">
      <div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
        <div class="user-base card-block ribbon-bookmark ribbon-warning">
          <span class="ribbon-inner">Outside Hitter</span>
          <span class="avatar img-bordered avatar-100" href="javascript:void(0)">
            <img src="<?= $user->getAvatarPath() ?>">
          </span>
          <h4 class="user-name"><?= $user->getFullname(); ?></h4>
        </div>
        <div class="card-block">
          <div class="row text-center mb-20">
            <div class="col-6">
              <div class="counter">
                <div class="counter-label total-completed">EVENTS</div>
                <div class="counter-number red-600"><?= $count['total'] ?></div>
              </div>
            </div>
            <div class="col-6">
              <div class="counter">
                <div class="counter-label">MATCH PLAYED</div>
                <div class="counter-number blue-600"><?= $count['match'] ?></div>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    Present
                  </td>
                  <td>
                    <div class="progress progress-xs mb-0">
                      <div class="progress-bar progress-bar-info bg-green-600" role="progressbar" aria-valuenow="<?= $count['ok'] ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?= $count['ok'] ?>%">
                      </div>
                    </div>
                  </td>
                  <td>
                    <?= $count['ok'] ?>%
                  </td>
                </tr>
                <tr>
                  <td>
                    Absent
                  </td>
                  <td>
                    <div class="progress progress-xs mb-0">
                      <div class="progress-bar progress-bar-info bg-red-600" role="progressbar" aria-valuenow="<?= $count['no']?>" aria-valuemin="0" aria-valuemax="100" style="width: <?= $count['no']?>%">
                      </div>
                    </div>
                  </td>
                  <td>
                    <?= $count['no']?>%
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card">
      <div class="card-header card-header-transparent">
        <h4 class="card-title">
          Edit Your Profile
        </h4>
      </div>
      <div class="card-block">
        <form method="post" name="submit-profile">
          <div class="row">
            <div class="form-group col-md-6">
              <input type="text" class="form-control" name="firstname" placeholder="First Name"
                autocomplete="off" value="<?= $user->firstname ?>" required/>
            </div>
            <div class="form-group col-md-6">
              <input type="text" class="form-control" name="lastname" placeholder="Last Name"
                autocomplete="off" value="<?= $user->lastname ?>" required/>
            </div>
          </div>
          <div class="form-group">
            <input type="email" class="form-control" name="email" placeholder="Email Address"
              autocomplete="off" disabled value="<?= $user->email ?>" />
          </div>
          <div class="row">
            <div class="col-7">
              <div class="input-group">
                <select name="position" class="col-12 form-control">
                  <option disabled="disabled" <?= (!$user->position) ? ' selected' :''; ?>>Role</option>
                  <option <?= ($user->position == 4) ? ' selected' :''; ?> value="4">Outside Hitter</option>
                  <option <?= ($user->position == 2) ? ' selected' :''; ?> value="2">Opposite</option>
                  <option <?= ($user->position == 3) ? ' selected' :''; ?> value="3">Middle Blocker</option>
                  <option <?= ($user->position == 1) ? ' selected' :''; ?> value="1">Setter</option>
                  <option <?= ($user->position == 5) ? ' selected' :''; ?> value="5">Libero</option>
                  <option <?= ($user->position == 6) ? ' selected' :''; ?> value="6">Coach</option>
                </select>
              </div>
            </div>
            <div class="col-5">
              <div class="input-group">
                <select class="col-12 form-control" name="numero">
                  <option disabled="disabled"  <?= (!$user->numero) ? ' selected' :''; ?>>Number</option>
                  <?php for ($i = 1; $i <= 22 ; $i++) : ?>
                    <option  <?= ($user->numero == $i) ? ' selected' :''; ?> value="<?= $i ?>"># <?= $i ?></option>
                  <?php endfor; ?>
                </select>
              </div>
            </div>
          </div>

          <div class="form-group mt-10 float-right">
            <button type="submit" class="btn btn-success btn-outline" name="submit-profile">
              <i class="icon wb-check"></i> Submit
          </div>
        </form>
      </div>
    </div>

    <div class="card">
      <div class="card-header card-header-transparent pb-0">
        <h4 class="card-title">
          <i class="icon wb-heart"></i>My Holidays
        </h4>
      </div>
      <div class="card-block mb-0 pt-10">
        <form method="post" name="submit-holiday">
          <div class="input-daterange" data-plugin="datepicker" data-date-format="yyyy-mm-dd" data-start-date="now">
            <div class="input-group col-5 p-0">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="icon wb-calendar" aria-hidden="true"></i>
                </span>
              </div>
              <input type="text" class="form-control m-0" name="start" required />
            </div>
            <div class="input-group col-5 p-0">
              <div class="input-group-prepend">
                <span class="input-group-text">to</span>
              </div>
              <input type="text" class="form-control m-0" name="end"  required/>
            </div>
            <button type="submit" name="submit-holiday" class="btn btn-primary btn-outline col-2 m-0"><i class="icon wb-plus-circle"></i></button>
          </div>
        </form>
      </div>

      <?php if ($holidays): ?>        
        <div class="card-block">
          <div class="table-responsive">
            <table class="table text-center">
              <tbody>
                <?php foreach ($holidays as $holiday): ?>            
                  <tr class="p-20">
                    <td>
                      <?php
                        $from = \DateTime::createFromFormat('Y-m-d H:i:s', $holiday->from);
                        echo $from->format('Y-m-d');
                      ?>
                    </td>
                    <td>
                      <i class="icon wb-arrow-right"></i>
                    </td>
                    <td>
                      <?php
                        $to = \DateTime::createFromFormat('Y-m-d H:i:s', $holiday->to);
                        echo $to->format('Y-m-d');
                      ?>
                    </td>
                    <td class="text-right">
                      <a href="javascript:void(0)" class="delete-holiday" data-id="<?= $holiday->id ?>">
                        <i class="icon wb-trash text-danger"></i>
                      </a>
                    </td>
                  </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      <?php endif ?>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Avatar</h3>
      </div>
      <div class="panel-body container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="cropper text-center" id="exampleFullCropper">
              <img src="/img/default-avatar.png" alt="...">
            </div>
            <div class="cropper-toolbar text-center">
              <div class="btn-group mb-20">
                <button type="button" class="btn btn-default btn-outline" data-cropper-method="clear" data-toggle="tooltip"
                  data-container="body">
                  <span class="cropper-tooltip">
                    <i class="icon wb-close" aria-hidden="true"></i> Clear
                  </span>
                </button>
                <label class="btn btn-primary mb-0 btn-outline" data-toggle="tooltip" for="inputImage" data-container="body">
                  <input type="file" class="hidden-xs-up" id="inputImage" name="file" accept="image/*">
                  <span class="cropper-tooltip">
                    <i class="icon wb-folder" aria-hidden="true"></i> Choose
                  </span>
                </label>
                <button type="button" id="uploadCropperData" class="btn btn-success btn-outline" data-toggle="tooltip"
                  data-container="body">
                  <span class="cropper-tooltip">
                    <i class="icon wb-download" aria-hidden="true"></i> Upload
                  </span>
                </button>
              </div>
            </div>
          </div>

          <div class="col-lg-12">
            <div class="cropper-preview clearfix" id="exampleFullCropperPreview">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>