<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-bookmark ribbon-warning">
      <div id="personalCompletedWidget" class="user-info card card-shadow text-center pb-20">
        <div class="user-base card-block ribbon-bookmark ribbon-warning">
          <span class="ribbon-inner">Outside Hitter</span>
          <a class="avatar img-bordered avatar-100" href="javascript:void(0)">
            <img alt="" src="/img/avatars/<?= $user->id ?>.png" onerror="if (this.src != '/img/default-avatar.png') this.src = '/img/default-avatar.png';">
          </a>
          <h4 class="user-name"><?= $user->getFullname(); ?></h4>
        </div>
        <div class="card-block">
          <div class="row text-center mb-20">
            <div class="col-6">
              <div class="counter">
                <div class="counter-label total-completed">EVENTS</div>
                <div class="counter-number red-600">1,628</div>
              </div>
            </div>
            <div class="col-6">
              <div class="counter">
                <div class="counter-label">MATCH PLAYED</div>
                <div class="counter-number blue-600">170</div>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    Present
                  </td>
                  <td>
                    <div class="progress progress-xs mb-0">
                      <div class="progress-bar progress-bar-info bg-green-600" role="progressbar" aria-valuenow="86" aria-valuemin="0" aria-valuemax="100" style="width: 86%">
                      </div>
                    </div>
                  </td>
                  <td>
                    86%
                  </td>
                </tr>
                <tr>
                  <td>
                    Absent
                  </td>
                  <td>
                    <div class="progress progress-xs mb-0">
                      <div class="progress-bar progress-bar-info bg-red-600" role="progressbar" aria-valuenow="68" aria-valuemin="0" aria-valuemax="100" style="width: 68%">
                      </div>
                    </div>
                  </td>
                  <td>
                    68%
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-lg-4">
    <div class="card">
      <div class="card-header card-header-transparent">
        <h4 class="card-title">
          My Holidays
        </h4>
      </div>
      <div class="card-block mb-0">
        <div class="input-daterange" data-plugin="datepicker">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="icon wb-calendar" aria-hidden="true"></i>
              </span>
            </div>
            <input type="text" class="form-control" name="start" />
          </div>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">to</span>
            </div>
            <input type="text" class="form-control" name="end" />
          </div>
          <div class="form-group mt-10 float-right">
            <button type="button" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>

      <div class="list-group m-0  has-actions">
        <a class="list-group-item">
          <div class="media">
            <div class="media-body">
              <h5 class="mt-0 mb-5">July, 20 2017  <i class="icon wb-arrow-right" aria-hidden="true"></i> July, 28 2017</h5>
            </div>
            <div class="item-actions">
                <span class="btn btn-pure btn-icon" data-toggle="list-visible"><i class="icon wb-trash" aria-hidden="true"></i></span>
              </div>
          </div>
        </a>
      </div>
    </div>

    <!-- Last comments -->
    <div class="panel" id="followers">
      <div class="panel-heading">
        <h3 class="panel-title">
          Followers
        </h3>
        <div class="panel-actions panel-actions-keep">
          <div class="dropdown">
            <a class="panel-action" id="examplePanelDropdown" data-toggle="dropdown" href="#"
              aria-expanded="false" role="button"><i class="icon wb-more-vertical" aria-hidden="true"></i></a>
            <div class="dropdown-menu dropdown-menu-bullet dropdown-menu-right" aria-labelledby="examplePanelDropdown"
              role="menu">
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-flag" aria-hidden="true"></i> Action</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-print" aria-hidden="true"></i> Another action</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-heart" aria-hidden="true"></i> Something else here</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-share" aria-hidden="true"></i> Separated link</a>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <ul class="list-group list-group-dividered list-group-full h-300" data-plugin="scrollable">
          <div data-role="container">
            <div data-role="content">
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-online" href="javascript:void(0)">
                      <img src="../../../global/portraits/9.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Willard Wood</span>
                    </div>
                    <small>@heavybutterfly920</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-away" href="javascript:void(0)">
                      <img src="../../../global/portraits/10.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-success btn-sm"><i class="icon wb-check" aria-hidden="true"></i>Following</button>
                    </div>
                    <div>
                      <span>Ronnie Ellis</span>
                    </div>
                    <small>@kingronnie24</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-busy" href="javascript:void(0)">
                      <img src="../../../global/portraits/11.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Gwendolyn Wheeler</span>
                    </div>
                    <small>@perttygirl66</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-off" href="javascript:void(0)">
                      <img src="../../../global/portraits/12.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Daniel Russell</span>
                    </div>
                    <small>@danieltiger08</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-online" href="javascript:void(0)">
                      <img src="../../../global/portraits/9.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Willard Wood</span>
                    </div>
                    <small>@heavybutterfly920</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-away" href="javascript:void(0)">
                      <img src="../../../global/portraits/10.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-success btn-sm"><i class="icon wb-check" aria-hidden="true"></i>Following</button>
                    </div>
                    <div>
                      <span>Ronnie Ellis</span>
                    </div>
                    <small>@kingronnie24</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-busy" href="javascript:void(0)">
                      <img src="../../../global/portraits/11.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Gwendolyn Wheeler</span>
                    </div>
                    <small>@perttygirl66</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <div class="pr-20">
                    <a class="avatar avatar-off" href="javascript:void(0)">
                      <img src="../../../global/portraits/12.jpg" alt="">
                      <i></i>
                    </a>
                  </div>
                  <div class="media-body w-full">
                    <div class="float-right">
                      <button type="button" class="btn btn-outline btn-default btn-sm">Follow</button>
                    </div>
                    <div>
                      <span>Daniel Russell</span>
                    </div>
                    <small>@danieltiger08</small>
                  </div>
                </div>
              </li>
            </div>
          </div>
        </ul>
      </div>
    </div>
</div>

<div class="col-lg-4">
  <div class="card">
    <div class="card-header card-header-transparent">
      <h4 class="card-title">
        Edit Your Profile
      </h4>
    </div>
    <div class="card-block">
      <?php $form->prepare(); // The correct enctype is set here ?>
      <?= $this->form()->openTag($form); ?>
        <div class="row">
          <div class="form-group col-md-6">
            <input type="text" class="form-control" name="firstname" placeholder="First Name"
              autocomplete="off" value="<?= $user->firstname ?>"/>
          </div>
          <div class="form-group col-md-6">
            <input type="text" class="form-control" name="lastname" placeholder="Last Name"
              autocomplete="off" value="<?= $user->lastname ?>"/>
          </div>
        </div>
        <div class="form-group">
          <input type="email" class="form-control" name="email" placeholder="Email Address"
            autocomplete="off" disabled value="<?= $user->email ?>" />
        </div>
        <div class="form-group">
          <input type="password" class="form-control" name="password" placeholder="Password"
            autocomplete="off" />
        </div>
        <div class="form-element">
            <label>Change your image</label>
            <?php $fileElement = $form->get('image-file'); ?>
            <?= $this->formFile($fileElement); ?>
        </div>
        <div class="form-group mt-10 float-right">
          <button type="button" class="btn btn-primary">Submit</button>
        </div>
      <?= $this->form()->closeTag(); ?>
    </div>
  </div>
  </div>
</div>