<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" style="border-collapse:collapse;height:100%;margin:0;padding:0;width:100%;background-color:#ffffff">
  <tbody>
    <tr>
      <td align="center" valign="top" style="height:100%;margin:0;padding:0;width:100%;border-top:0">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
          <tbody>
            <tr>
              <td align="center" valign="top" style="background:#e6a56a url(&quot;https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg&quot;) no-repeat top/cover;background-color:#e6a56a;background-image:url(https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg);background-repeat:no-repeat;background-position:top;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:80px">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">

                                        <h1 style="display:block;margin:0;padding:0;color:#ffffff;font-family:Georgia;font-size:60px;font-style:normal;font-weight:normal;line-height:200%;letter-spacing:normal;text-align:center">
                                          <span style="font-family:arial,helvetica neue,helvetica,sans-serif">Volley-Ball.eu</span>
                                        </h1>

                                        <h2 style="text-align:center;display:block;margin:0;padding:0;color:#ffffff;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
                                          <span style="font-family:arial,helvetica neue,helvetica,sans-serif">
                                            <span style="font-size:24px">Gestion d'entrainements,<br>
                                            &nbsp;matchs et statistiques</span>
                                          </span>
                                        </h2>
                                        <p style="margin:10px 0;padding:0;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">&nbsp;</p>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:20px 18px 0px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate!important;border-radius:3px;background-color:#68b3c8">
                                  <tbody>
                                    <tr>
                                      <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:20px">
                                        <a title="Aller au site" href="<?= $baseUrl ?>" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">Aller au site</a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:0">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding:9px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background:#ffffff">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding:0 9px">
                                        <table align="right" border="0" cellpadding="0" cellspacing="0" width="176" style="border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="top">
                                                <img alt="" src="https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/59036637-4927-43f8-8d6d-86bbaa5ccd86.png" width="100" style="max-width:100px;border:0;height:auto;outline:none;text-decoration:none;vertical-align:bottom">
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="352" style="border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td valign="top" style="word-break:break-word;color:#202020;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">
                                                <h3 style="text-align:center;display:block;margin:0;padding:0;color:#393939;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
                                                  <u><?= $user->getFullname() ?></u>
                                                </h3>
                                                <div style="text-align:center">
                                                  <br>
                                                  <span style="color:#696969">
                                                    <em><?= nl2br($comment->comment) ?></em>
                                                  </span>
                                                </div>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:18px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top:2px solid #eaeaea;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="center" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse" width="50%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding:0px 18px 9px;color:#323232;word-break:break-word;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center;border:solid 1px #cccccc">
                                        <h2 style="display:block;margin:0;padding:0;color:#ffffff;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal;text-align:center">
                                          <a href="http://volley-ball.eu" style="color:#68b3c8;font-size:24px;text-decoration:none;font-family:arial,helvetica neue,helvetica,sans-serif;font-weight:normal" target="_blank"><?= $event->name ?></a>
                                        </h2>
                                        <p style="color:#323232;margin:10px 0;padding:0;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">
                                          <br>
                                          <strong style="color:#808080;font-weight:900">
                                            <?= $event->place ?>
                                          </strong>
                                          <br>
                                          <a href="https://maps.google.com/?q=<?= $event->address . '+' . $event->city . '+' . $event->zipCode ?>" style="color:#000000;font-weight:normal;text-decoration:underline" target="_blank"><?= $event->address ?><br>
                                          <?= $event->zipCode ?> <?= $event->city ?></a>
                                        </p>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                                <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse" width="50%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding:0px 18px 9px;color:#323232;wdord-break:break-word;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">
                                        <table border="0" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border:1px solid #cccccc;border-collapse:collapse;float:right;">
                                          <tbody>
                                            <tr>
                                              <td align="center" style="padding:5px" valign="top" width="160">
                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                  <tbody>
                                                    <tr>
                                                      <td align="center" style="background-color:#fd9f1b;color:#ffffff;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:bold;padding-top:10px;padding-bottom:10px;text-align:center" valign="top"><?= \Application\Service\Date::toFr($date->format('F')) ?></td>
                                                    </tr>
                                                    <tr>
                                                      <td align="center" style="color:#000;font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:100%;padding-top:5px;padding-bottom:5px;text-align:center" valign="top"><?= \Application\Service\Date::toFr($date->format('l')) ?></td>
                                                    </tr>
                                                    <tr>
                                                      <td align="center" style="color:#fd9f1b;font-family:Helvetica,Arial,sans-serif;font-size:60px;font-weight:bold;line-height:100%;text-align:center" valign="top"><?= \Application\Service\Date::toFr($date->format('d')) ?></td>
                                                    </tr>
                                                    <tr>
                                                      <td align="center" style="color:#000;font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:100%;padding-top:5px;padding-bottom:5px;text-align:center" valign="top"><?= \Application\Service\Date::toFr($date->format('H\:i')) ?></td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:40px 18px 0px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding:0px 18px 9px;line-height:150%;word-break:break-word;color:#202020;font-family:Helvetica;font-size:18px;text-align:center">
                                        <h3 style="text-align:center!important;display:block;margin:0;padding:0;color:#393939;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">Votre disponibilité pour l'événement ?</h3>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:0;padding-bottom:80px">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="200" style="border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate!important;border-radius:3px;background-color:#d5e5a3">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:15px">
                                                <a title="Présent" href="<?= $baseUrl . '/disponibility/response/' . $event->id . '/' . \Application\Model\Disponibility::RESP_OK ?>" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">Présent</a>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="200" style="border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate!important;border-radius:3px;background-color:#ff8f5e">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:15px">
                                                <a href="<?= $baseUrl . '/disponibility/response/' . $event->id . '/' . \Application\Model\Disponibility::RESP_NO ?>" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">Absent</a>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="200" style="border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate!important;border-radius:3px;background-color:#b8d8d8">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:15px">
                                                <a href="<?= $baseUrl . '/disponibility/response/' . $event->id . '/' . \Application\Model\Disponibility::RESP_UNCERTAIN ?>" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">Incertain</a>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:0;padding-bottom:40px">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <a href="https://maps.google.com/?q=<?= $event->address . '+' . $event->city . '+' . $event->zipCode ?>">
                          <img src="https://maps.googleapis.com/maps/api/staticmap?center=<?= $event->address . '+' . $event->city . '+' . $event->zipCode ?>&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7C<?= $event->address . '+' . $event->city . '+' . $event->zipCode ?>&key=AIzaSyDq7_lf88qeeR3EaqtxvX07e7WgdvjUvr4">
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:18px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top:2px solid #eaeaea;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#656565;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">

                                        <p style="font-size:16px!important;text-align:center!important;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;line-height:150%">Cet email a été généré et envoyé automatiquement.<br>
                                        Merci de ne pas y répondre.</p>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td align="center" valign="top" style="padding:9px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td align="center" style="padding-left:9px;padding-right:9px">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="top" style="padding-top:9px;padding-right:9px;padding-left:9px">
                                                <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                  <tbody>
                                                    <tr>
                                                      <td align="center" valign="top">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:10px;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>
                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="http://volley-ball.eu/welcome" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-link-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table>
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:10px;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>
                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="http://www.twitter.com/yucky_" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-twitter-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:0;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>

                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="mailto:volleyball.eu@gmail.com" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-forwardtofriend-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>