<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" style="border-collapse:collapse;height:100%;margin:0;padding:0;width:100%;background-color:#ffffff">
  <tbody>
    <tr>
      <td align="center" valign="top" style="height:100%;margin:0;padding:0;width:100%;border-top:0">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
          <tbody>
            <tr>
              <td align="center" valign="top" style="background:#e6a56a url(&quot;https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg&quot;) no-repeat top/cover;background-color:#e6a56a;background-image:url(https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/a3fc15e8-885e-4073-a134-951d2273d71d.jpg);background-repeat:no-repeat;background-position:top;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:80px">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">

                                        <h1 style="display:block;margin:0;padding:0;color:#ffffff;font-family:Georgia;font-size:60px;font-style:normal;font-weight:normal;line-height:200%;letter-spacing:normal;text-align:center">
                                          <span style="font-family:arial,helvetica neue,helvetica,sans-serif">Volley-Ball.eu</span>
                                        </h1>

                                        <h2 style="text-align:center;display:block;margin:0;padding:0;color:#ffffff;font-family:Helvetica;font-size:30px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
                                          <span style="font-family:arial,helvetica neue,helvetica,sans-serif">
                                            <span style="font-size:24px">Gestion d'entrainements,<br>
                                            &nbsp;matchs et statistiques</span>
                                          </span>
                                        </h2>
                                        <p style="margin:10px 0;padding:0;color:#ffffff;font-family:Helvetica;font-size:20px;line-height:150%;text-align:center">&nbsp;</p>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:20px 18px 0px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:80px;padding-bottom:0">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding:9px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background:#ffffff">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding:0 9px">
                                        <table align="right" border="0" cellpadding="0" cellspacing="0" width="176" style="border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="top">
                                                <img alt="" src="https://gallery.mailchimp.com/c294e5e6fcd7996580bb94ded/images/59036637-4927-43f8-8d6d-86bbaa5ccd86.png" width="100" style="max-width:100px;border:0;height:auto;outline:none;text-decoration:none;vertical-align:bottom">
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="352" style="border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td valign="top" style="word-break:break-word;color:#202020;font-family:Helvetica;font-size:18px;line-height:150%;text-align:center">
                                                <h3 style="text-align:center;display:block;margin:0;padding:0;color:#393939;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:125%;letter-spacing:normal">
                                                  Changement de mot de passe
                                                </h3>
                                                <div style="text-align:center">
                                                  <br>
                                                  <span style="color:#696969">
                                                    Vous avez fait une demande de réinitialisation de mot de passe. Si vous n'êtes pas à l'origine de cette demande, merci d'ignorer cet email.
                                                  </span>
                                                </div>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                                          <tbody>
                                            <tr>
                                              <td style="min-width:100%;padding:18px">
                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top:2px solid #eaeaea;border-collapse:collapse">
                                                  <tbody>
                                                    <tr>
                                                      <td>
                                                        <span>
                                                        </span>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;padding-top:0;padding-bottom:80px">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                          <tbody>
                            <tr>
                              <td valign="top">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td valign="top">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate!important;border-radius:3px;background-color:#68b3c8">
                                                  <tbody>
                                                    <tr>
                                                      <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:15px">
                                                        <a title="Présent" href="<?= $url ?>" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">Modifier</a>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="center" valign="top" style="background:#ffffff none no-repeat center/cover;background-color:#ffffff;background-image:none;background-repeat:no-repeat;background-position:center;background-size:cover;border-top:0;border-bottom:0;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;max-width:600px!important">
                  <tbody>
                    <tr>
                      <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                          <tbody>
                            <tr>
                              <td style="min-width:100%;padding:18px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top:2px solid #eaeaea;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                        </span>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td valign="top" style="padding-top:9px">
                                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%;min-width:100%;border-collapse:collapse" width="100%">
                                  <tbody>
                                    <tr>
                                      <td valign="top" style="padding-top:0;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#656565;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">

                                        <p style="font-size:16px!important;text-align:center!important;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;line-height:150%">Cet email a été généré et envoyé automatiquement.<br>
                                        Merci de ne pas y répondre.</p>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                          <tbody>
                            <tr>
                              <td align="center" valign="top" style="padding:9px">
                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                  <tbody>
                                    <tr>
                                      <td align="center" style="padding-left:9px;padding-right:9px">
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                          <tbody>
                                            <tr>
                                              <td align="center" valign="top" style="padding-top:9px;padding-right:9px;padding-left:9px">
                                                <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                  <tbody>
                                                    <tr>
                                                      <td align="center" valign="top">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:10px;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>
                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="http://volley-ball.eu/welcome" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-link-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table>
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:10px;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>
                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="http://www.twitter.com/yucky_" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-twitter-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse">
                                                          <tbody>
                                                            <tr>
                                                              <td valign="top" style="padding-right:0;padding-bottom:9px">
                                                                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                  <tbody>
                                                                    <tr>
                                                                      <td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px">
                                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse">
                                                                          <tbody>
                                                                            <tr>

                                                                              <td align="center" valign="middle" width="24">
                                                                                <a href="mailto:volleyball.eu@gmail.com" target="_blank">
                                                                                  <img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-forwardtofriend-48.png" style="display:block;border:0;height:auto;outline:none;text-decoration:none" height="24" width="24">
                                                                                </a>
                                                                              </td>
                                                                            </tr>
                                                                          </tbody>
                                                                        </table>
                                                                      </td>
                                                                    </tr>
                                                                  </tbody>
                                                                </table>
                                                              </td>
                                                            </tr>
                                                          </tbody>
                                                        </table>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>