<div class="calendar-container">
  <div id="calendar"></div>
  <?php if ($adminGroups): ?>
	  <div class="col-12 text-center mt-10">
	  	<button class="btn btn-primary btn-outline col-12 col-md-6 col-lg-4" data-toggle="modal" data-target="#addNewEvent"><i class="icon wb-plus"></i> Event</button><br>
	  	<small>Or select date in calendar</small>
	  </div>
  <?php endif ?>

  <!-- Edit Dialog -->
  <?= $this->partial('partial/event-detail-side.phtml') ?>
  <?= $this->partial('partial/add-event.phtml') ?>
</div>